"use client";

import { useMemo, useState } from "react";
import { FinalSettlementModal } from "@/components/finance/FinalSettlementModal";
import type { FinalSettlement, SettlementStatus } from "@/types/construction";

const initial: FinalSettlement[] = [
  { id: "set-1", packageName: "Civil & Superstructure", contractor: "CoreBuild Contractors", cumulativeRaBills: 184000000, finalCertifiedAmount: 181500000, retentionAmount: 9150000, dlpExpiry: "2026-07-31", punchItemsClosed: true, noClaimsCertificate: "NCC-CIV-001.pdf", finalCompletionCertificate: "FCC-CIV-001.pdf", status: "Approved" },
  { id: "set-2", packageName: "MEP & Services", contractor: "VoltEdge MEP", cumulativeRaBills: 96000000, finalCertifiedAmount: 101000000, retentionAmount: 5050000, dlpExpiry: "2026-12-31", punchItemsClosed: false, status: "In Review" },
  { id: "set-3", packageName: "Finishes & Facade", contractor: "FacadeWorks", cumulativeRaBills: 72000000, finalCertifiedAmount: 70000000, retentionAmount: 3500000, dlpExpiry: "2026-06-30", punchItemsClosed: true, noClaimsCertificate: "NCC-FIN-001.pdf", finalCompletionCertificate: "FCC-FIN-001.pdf", status: "Settled & Closed" },
];
const colors: Record<SettlementStatus, string> = { Draft: "#94a3b8", "In Review": "#fbbf24", Approved: "#60a5fa", "Settled & Closed": "#34d399" };
const money = (value: number) => value >= 10000000 ? `₹${(value / 10000000).toFixed(2)} Cr` : `₹${(value / 100000).toFixed(2)} Lakh`;

export default function SettlementsPage() { const [settlements, setSettlements] = useState(initial); const [selected, setSelected] = useState<FinalSettlement | null>(null); const closed = settlements.filter((item) => item.status === "Settled & Closed").length; const totalRetention = useMemo(() => settlements.reduce((sum, item) => sum + item.retentionAmount, 0), [settlements]); const save = (item: FinalSettlement) => { setSettlements((current) => current.map((entry) => entry.id === item.id ? item : entry)); setSelected(null); };
  return <main style={pageStyle}><div style={{ maxWidth: 1320, margin: "0 auto", display: "grid", gap: 22 }}><header><div style={eyebrow}>Finance / Commercial Closeout</div><h1 style={heading}>Final Account Settlements</h1><p style={muted}>Reconcile certified final quantities, clear DLP obligations, and release retention only when controls pass.</p></header><section style={cards}><div style={panel}><div style={eyebrow}>Contract Closeout Status</div><strong style={metric}>{Math.round(closed / settlements.length * 100)}%</strong><div style={bar}><span style={{ width: `${closed / settlements.length * 100}%` }} /></div></div><div style={panel}><div style={eyebrow}>Retention ledger</div><strong style={metric}>{money(totalRetention)}</strong></div></section><section style={panel}><div style={eyebrow}>Settlement progression</div><div style={{ overflowX: "auto" }}><table style={{ width: "100%", minWidth: 900, borderCollapse: "collapse" }}><thead><tr>{["Package / Contractor", "RA bills", "Final certified", "Reconciliation", "Retention", "Status", "Action"].map((label) => <th key={label} style={th}>{label}</th>)}</tr></thead><tbody>{settlements.map((item) => <tr key={item.id}><td style={td}><strong>{item.packageName}</strong><div style={muted}>{item.contractor}</div></td><td style={td}>{money(item.cumulativeRaBills)}</td><td style={td}>{money(item.finalCertifiedAmount)}</td><td style={{ ...td, color: item.cumulativeRaBills === item.finalCertifiedAmount ? "#86efac" : "#fbbf24" }}>{item.cumulativeRaBills === item.finalCertifiedAmount ? "Reconciled" : `${money(item.finalCertifiedAmount - item.cumulativeRaBills)} variance`}</td><td style={td}>{money(item.retentionAmount)}</td><td style={td}><span style={{ ...badge, color: colors[item.status], borderColor: `${colors[item.status]}66` }}>{item.status}</span></td><td style={td}><button type="button" onClick={() => setSelected(item)} style={button}>Review</button></td></tr>)}</tbody></table></div></section>{selected ? <FinalSettlementModal settlement={selected} onClose={() => setSelected(null)} onSave={save} /> : null}</div></main>; }
const pageStyle = { minHeight: "100vh", background: "#050816", color: "#e2e8f0", padding: "32px 24px 64px" }; const heading = { margin: "8px 0 0", fontSize: 42 }; const eyebrow = { color: "#7dd3fc", fontSize: 11, letterSpacing: ".16em", textTransform: "uppercase" as const }; const muted = { color: "#94a3b8", fontSize: 13, lineHeight: 1.5 }; const panel = { background: "rgba(15,23,42,.82)", border: "1px solid rgba(148,163,184,.2)", borderRadius: 18, padding: 20 }; const cards = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(240px,1fr))", gap: 16 }; const metric = { display: "block", marginTop: 10, fontSize: 30 }; const bar = { height: 9, marginTop: 16, background: "rgba(148,163,184,.18)", borderRadius: 99, overflow: "hidden" as const }; const th = { textAlign: "left" as const, padding: "12px 10px", color: "#a5f3fc", fontSize: 11, textTransform: "uppercase" as const, borderBottom: "1px solid rgba(148,163,184,.2)" }; const td = { padding: "14px 10px", borderBottom: "1px solid rgba(148,163,184,.12)", verticalAlign: "top" as const }; const badge = { display: "inline-block", border: "1px solid", background: "rgba(148,163,184,.1)", borderRadius: 99, padding: "6px 9px", fontSize: 11, fontWeight: 800 }; const button = { border: "1px solid rgba(96,165,250,.4)", background: "rgba(96,165,250,.12)", color: "#eff6ff", borderRadius: 9, padding: "9px 13px", fontWeight: 800, cursor: "pointer" }; 
