import type { DocumentSignatureRecord } from "@/types/construction";

const signedDocuments: DocumentSignatureRecord[] = [
  { id: "ledger-1", projectId: "proj-1", documentName: "GFC-STR-04 / Level 04 Slab", documentType: "GFC Drawing", signer: "Ananya Mehta", stakeholder: "Architect", organization: "Mehta Design Associates", credential: "COA / AOR-1184", signedAt: "2026-08-24T07:40:00.000Z", certificateHash: "a8e0e0a8b4c177e09580bf4d4a2df21d9c3f7b9fbd6a6b590ef6ec457e7798d1", verificationStatus: "Verified", x: 72, y: 72 },
  { id: "ledger-2", projectId: "proj-1", documentName: "RA-08 / Interim Payment Certificate", documentType: "RA Billing Certificate", signer: "Nikhil Shah", stakeholder: "Client", organization: "Quadillar Asset Holdings", credential: "Authorized Client Signatory", signedAt: "2026-08-23T15:20:00.000Z", certificateHash: "47f851b64cdb4f7f4b77e3fdcbeb3f1dd9fb55fbc89f6793ecf4be5e62ae9fb0", verificationStatus: "Verified", x: 72, y: 72 },
];

export function VerificationTelemetry() {
  const resolved = 11;
  const open = 4;
  const qualityIndex = Math.round((resolved / (resolved + open)) * 100);
  return <section className="mt-6 grid gap-3 xl:grid-cols-[1.15fr_.85fr]"><div className="surface-shell px-5 py-4"><div className="flex items-center justify-between gap-3"><div><div className="text-[11px] font-medium tracking-[0.14em] text-neutral-400 uppercase">Signed Document Verification Ledger</div><div className="mt-2 text-lg font-medium text-neutral-100">Recent trusted releases</div></div><a href="/governance/signatures" className="text-[11px] font-medium tracking-[0.12em] text-sky-300 uppercase no-underline">Open vault</a></div><div className="mt-4 space-y-2">{signedDocuments.map((record) => <div key={record.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/[0.06] bg-white/[0.02] px-3 py-3"><div className="min-w-0"><div className="truncate text-sm text-neutral-100">{record.documentName}</div><div className="mt-1 truncate text-[11px] font-mono tracking-[0.08em] text-neutral-500">{record.signer} · {record.documentType}</div></div><span className="shrink-0 rounded-full bg-emerald-500/10 px-2 py-1 text-[10px] font-medium tracking-[0.1em] text-emerald-200 uppercase">Verified</span></div>)}</div></div><div className="surface-shell px-5 py-4"><div className="flex items-center justify-between gap-3"><div><div className="text-[11px] font-medium tracking-[0.14em] text-neutral-400 uppercase">AI Visual Quality Index</div><div className="mt-2 text-4xl font-medium tracking-tight text-neutral-100">{qualityIndex}<span className="text-base text-neutral-500"> / 100</span></div></div><a href="/quality/vision-ai" className="text-[11px] font-medium tracking-[0.12em] text-sky-300 uppercase no-underline">Inspect flags</a></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/[0.06]"><div className="h-full rounded-full bg-emerald-400" style={{ width: `${qualityIndex}%` }} /></div><div className="mt-3 grid grid-cols-2 gap-2 text-center"><div className="rounded-xl border border-white/[0.06] bg-white/[0.02] px-2 py-3"><div className="text-lg text-emerald-200">{resolved}</div><div className="text-[10px] tracking-[0.1em] text-neutral-500 uppercase">Resolved</div></div><div className="rounded-xl border border-white/[0.06] bg-white/[0.02] px-2 py-3"><div className="text-lg text-amber-200">{open}</div><div className="text-[10px] tracking-[0.1em] text-neutral-500 uppercase">Open flags</div></div></div></div></section>;
}
