"use client";

import { useState } from "react";
import { createOrUpdateMeetingMinutes, updateMeetingActionStatus } from "@/app/lib/services";
import type { MeetingActionItem, MeetingActionStatus, MeetingMinutesRecord } from "@/types/construction";

export function MeetingDocument({ initialMeeting, onSaved }: { initialMeeting: MeetingMinutesRecord; onSaved: (meeting: MeetingMinutesRecord) => void }) {
  const [meeting, setMeeting] = useState(initialMeeting);
  const [agenda, setAgenda] = useState(initialMeeting.agendaNotes);
  const [actionItems, setActionItems] = useState(initialMeeting.actionItems);
  const [newAction, setNewAction] = useState({ description: "", assignee: "Contractor", dueDate: "" });
  const locked = meeting.published;
  const save = async (next: MeetingMinutesRecord) => { const saved = await createOrUpdateMeetingMinutes(next); if (saved) { setMeeting(saved); onSaved(saved); } };
  const publish = () => void save({ ...meeting, agendaNotes: agenda, actionItems, published: true, publishedAt: new Date().toISOString(), publishedBy: "Project Manager" });
  const addAction = () => { if (locked || !newAction.description.trim()) return; const item: MeetingActionItem = { id: `act-${Date.now()}`, description: newAction.description, assignee: newAction.assignee, dueDate: newAction.dueDate || new Date().toISOString().slice(0, 10), status: "To Do" }; setActionItems((current) => [...current, item]); setNewAction({ description: "", assignee: "Contractor", dueDate: "" }); };
  const moveAction = async (item: MeetingActionItem, status: MeetingActionStatus) => { if (locked) return; const updated = await updateMeetingActionStatus(meeting.id, item.id, status); if (updated) { setMeeting(updated); setActionItems(updated.actionItems); onSaved(updated); } else { setActionItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, status } : entry)); } };
  const print = () => { const printWindow = window.open("", "_blank"); if (!printWindow) return; printWindow.document.write(`<html><head><title>${meeting.meetingNumber}</title><style>body{font-family:Arial;padding:40px;color:#172033}li{margin:8px 0}.stamp{border:3px solid #166534;color:#166534;padding:12px;text-align:center;font-weight:700}</style></head><body><h1>Quadillar LiveView</h1><p>${meeting.meetingNumber} · ${meeting.title} · ${new Date(meeting.meetingDate).toLocaleDateString()}</p><div class='stamp'>${meeting.published ? "PUBLISHED MOM" : "DRAFT MOM"}</div><h3>Attendees</h3><ul>${meeting.attendees.map((attendee) => `<li>${attendee.name} (${attendee.role}) - ${attendee.present ? "Present" : "Absent"}</li>`).join("")}</ul><h3>Agenda notes</h3><p>${agenda}</p><h3>Action items</h3><ul>${actionItems.map((item) => `<li>${item.description} - ${item.assignee} - ${item.status} - due ${item.dueDate}</li>`).join("")}</ul></body></html>`); printWindow.document.close(); printWindow.focus(); printWindow.print(); };
  return <section style={panel}><div style={header}><div><div style={eyebrow}>Meeting document</div><h2 style={{ margin: "6px 0 0", fontSize: 25 }}>{meeting.meetingNumber} · {meeting.title}</h2></div><span style={badge(locked)}>{locked ? "Published / Locked" : "Draft"}</span></div><div><div style={eyebrow}>Attendees</div><div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 10 }}>{meeting.attendees.map((attendee) => <button disabled={locked} type="button" key={attendee.id} onClick={() => setMeeting((current) => ({ ...current, attendees: current.attendees.map((item) => item.id === attendee.id ? { ...item, present: !item.present } : item) }))} style={{ ...attendeeButton, opacity: attendee.present ? 1 : 0.55 }}>{attendee.present ? "✓" : "○"} {attendee.name} / {attendee.role}</button>)}</div></div><label style={labelStyle}>Agenda notes<textarea disabled={locked} value={agenda} onChange={(event) => setAgenda(event.target.value)} style={{ ...inputStyle, minHeight: 100, resize: "vertical" }} /></label><div><div style={eyebrow}>Action item board</div><div style={board}>{(["To Do", "In Progress", "Done"] as const).map((status) => <div key={status} style={column}><div style={columnTitle}>{status}</div>{actionItems.filter((item) => item.status === status).map((item) => <div key={item.id} style={actionCard}><div style={{ color: "#f8fafc", fontWeight: 700 }}>{item.description}</div><div style={{ color: "#94a3b8", fontSize: 12, marginTop: 6 }}>{item.assignee} · due {item.dueDate}</div><select disabled={locked} value={item.status} onChange={(event) => void moveAction(item, event.target.value as MeetingActionStatus)} style={{ ...inputStyle, marginTop: 9, padding: "7px" }}><option>To Do</option><option>In Progress</option><option>Done</option></select></div>)}</div>)}</div>{!locked && <div style={newActionGrid}><input placeholder="Action item" value={newAction.description} onChange={(event) => setNewAction((current) => ({ ...current, description: event.target.value }))} style={inputStyle} /><input placeholder="Assignee role" value={newAction.assignee} onChange={(event) => setNewAction((current) => ({ ...current, assignee: event.target.value }))} style={inputStyle} /><input type="date" value={newAction.dueDate} onChange={(event) => setNewAction((current) => ({ ...current, dueDate: event.target.value }))} style={inputStyle} /><button type="button" onClick={addAction} style={secondary}>Add action</button></div>}</div><div style={{ display: "flex", justifyContent: "flex-end", gap: 10 }}><button type="button" onClick={print} style={secondary}>Print MOM PDF</button>{!locked && <button type="button" onClick={() => void save({ ...meeting, agendaNotes: agenda, actionItems, attendees: meeting.attendees })} style={secondary}>Save draft</button>}{!locked && <button type="button" onClick={publish} style={primary}>Publish MOM</button>}</div></section>;
}

const panel = { background: "#0b1220", border: "1px solid #1e293b", borderRadius: 20, padding: 22, color: "#e2e8f0", display: "grid", gap: 20 };
const header = { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 };
const eyebrow = { color: "#7dd3fc", fontSize: 11, letterSpacing: "0.14em", textTransform: "uppercase" as const };
const badge = (locked: boolean) => ({ borderRadius: 999, padding: "7px 10px", background: locked ? "rgba(34,197,94,0.12)" : "rgba(245,158,11,0.12)", color: locked ? "#bbf7d0" : "#fde68a", fontSize: 11, fontWeight: 700 });
const attendeeButton = { border: "1px solid #334155", borderRadius: 999, background: "#111827", color: "#cbd5e1", padding: "8px 10px", cursor: "pointer" };
const labelStyle = { display: "grid", gap: 7, color: "#cbd5e1", fontSize: 12 };
const inputStyle = { width: "100%", boxSizing: "border-box" as const, background: "#111827", border: "1px solid #334155", borderRadius: 9, color: "#f8fafc", padding: "10px" };
const board = { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 12, marginTop: 10 };
const column = { minHeight: 150, background: "#111827", border: "1px solid #1e293b", borderRadius: 12, padding: 10 };
const columnTitle = { color: "#94a3b8", fontSize: 11, letterSpacing: "0.12em", textTransform: "uppercase" as const, marginBottom: 9 };
const actionCard = { background: "#0b1220", border: "1px solid #334155", borderRadius: 10, padding: 10, marginBottom: 8 };
const newActionGrid = { display: "grid", gridTemplateColumns: "1.5fr 1fr 0.8fr auto", gap: 8, marginTop: 12 };
const primary = { border: 0, borderRadius: 10, background: "#2563eb", color: "#eff6ff", padding: "10px 14px", fontWeight: 700, cursor: "pointer" };
const secondary = { border: "1px solid #334155", borderRadius: 10, background: "transparent", color: "#cbd5e1", padding: "10px 14px", cursor: "pointer" };
