"use client";

import { useState } from "react";
import { BackchargeModal } from "@/components/finance/BackchargeModal";
import type { BackchargeRecord, BackchargeStatus } from "@/types/construction";

const initial: BackchargeRecord[] = [{ id: "bc-01", projectId: "proj-1", debitNumber: "DN-026", vendor: "CoreBuild Contractors", category: "Damaged Works", description: "Rework of damaged waterproofing membrane at podium.", amount: 185000, status: "Issued", issuedAt: "2026-08-25" }, { id: "bc-02", projectId: "proj-1", debitNumber: "DN-025", vendor: "SteelSpan India", category: "Material Misuse", description: "Unapproved cutting loss above allowance.", amount: 301000, status: "Under Dispute", rebuttal: "Awaiting joint reconciliation of cutting list.", issuedAt: "2026-08-21" }, { id: "bc-03", projectId: "proj-1", debitNumber: "DN-024", vendor: "VoltEdge MEP", category: "Safety Fines", description: "Repeated LOTO non-compliance fine.", amount: 128000, status: "Certified by PMC", issuedAt: "2026-08-18" }];
const colors: Record<BackchargeStatus, string> = { Issued: "#fbbf24", "Under Dispute": "#fb923c", "Certified by PMC": "#60a5fa", "Debited in IPC": "#34d399" };

export default function BackchargesPage() { const [items, setItems] = useState(initial); const [selected, setSelected] = useState<BackchargeRecord | null>(null); const add = () => setSelected({ id: `bc-${Date.now()}`, projectId: "proj-1", debitNumber: `DN-${items.length + 27}`, vendor: "", category: "Damaged Works", description: "", amount: 0, status: "Issued", issuedAt: new Date().toISOString() }); return <main style={page}><div style={container}><header style={header}><div><div style={eyebrow}>Finance / vendor recovery</div><h1 style={title}>Subcontractor backcharge & debit recovery</h1><p style={muted}>Issue, dispute, certify, and push approved contra-charges into vendor IPCs.</p></div><button type="button" onClick={add} style={button}>Issue backcharge</button></header><section style={panel}><div style={eyebrow}>Contra-charge register</div><div style={tableWrap}><table style={table}><thead><tr>{["Debit / vendor", "Category", "Amount", "Status", "Action"].map((heading) => <th key={heading} style={th}>{heading}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={item.id}><td style={td}><strong>{item.debitNumber}</strong><div style={muted}>{item.vendor}</div></td><td style={td}>{item.category}<div style={muted}>{item.description}</div></td><td style={td}>₹{item.amount.toLocaleString("en-IN")}</td><td style={{ ...td, color: colors[item.status], fontWeight: 800 }}>{item.status}</td><td style={td}><button type="button" onClick={() => setSelected(item)} style={button}>Open recovery</button></td></tr>)}</tbody></table></div></section>{selected && <BackchargeModal backcharge={selected} onClose={() => setSelected(null)} onSave={(updated) => { setItems((current) => current.some((item) => item.id === updated.id) ? current.map((item) => item.id === updated.id ? updated : item) : [updated, ...current]); setSelected(null); }} />}</div></main>; }
const page: React.CSSProperties = { minHeight: "100vh", background: "#050816", color: "#e2e8f0", padding: 28 }; const container: React.CSSProperties = { maxWidth: 1300, margin: "0 auto" }; const header: React.CSSProperties = { display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 18, flexWrap: "wrap", marginBottom: 24 }; const eyebrow: React.CSSProperties = { color: "#67e8f9", fontSize: 11, letterSpacing: ".16em", textTransform: "uppercase" }; const title: React.CSSProperties = { margin: "8px 0 0", fontSize: 38 }; const muted: React.CSSProperties = { color: "#94a3b8", fontSize: 12, marginTop: 5 }; const button: React.CSSProperties = { border: "1px solid #334155", borderRadius: 8, background: "#0ea5e9", color: "white", padding: "9px 12px", fontWeight: 800, cursor: "pointer" }; const panel: React.CSSProperties = { background: "#0b1220", border: "1px solid #1e293b", borderRadius: 16, padding: 20 }; const tableWrap: React.CSSProperties = { overflowX: "auto", marginTop: 16 }; const table: React.CSSProperties = { width: "100%", minWidth: 850, borderCollapse: "collapse" }; const th: React.CSSProperties = { padding: 12, textAlign: "left", color: "#64748b", fontSize: 10, textTransform: "uppercase", borderBottom: "1px solid #263449" }; const td: React.CSSProperties = { padding: 13, borderBottom: "1px solid #1f2937", verticalAlign: "top", fontSize: 13 };