"use client";

export function SiteGisAlertWidget() {
  const zones = ["North Tower", "Core shell", "Temporary power yard"];
  const alerts = [
    { time: "08:45", channel: "WhatsApp", title: "Crane wind threshold", role: "Site Supervisor" },
    { time: "08:18", channel: "SMS", title: "Restricted weather ops", role: "Safety Officer" },
    { time: "07:52", channel: "WhatsApp", title: "Hot work permit warning", role: "HSE Manager" },
  ];

  return <section className="mt-6 grid gap-3 xl:grid-cols-2"><div className="surface-shell px-5 py-4"><div className="flex items-center justify-between gap-3"><div><div className="text-[11px] font-medium tracking-[0.14em] text-neutral-400 uppercase">Site GIS Quick-View</div><div className="mt-2 text-lg font-medium text-neutral-100">Plot zones & crane hazard radii</div></div><a href="/site/gis" className="text-[11px] font-medium tracking-[0.12em] text-sky-300 uppercase no-underline">Open GIS</a></div><div className="relative mt-4 h-28 overflow-hidden border border-cyan-400/20 bg-[linear-gradient(135deg,#173b3b,#665b37)]"><div className="absolute inset-3 border-2 border-cyan-300/80" /><div className="absolute left-[42%] top-[18%] h-[58%] w-[24%] border border-white/80 bg-white/20" /><div className="absolute left-[58%] top-[8%] h-[85%] w-[34%] rounded-full border border-dashed border-amber-300/90 bg-amber-300/10" /><div className="absolute left-[20%] top-[43%] h-3 w-3 rounded-full bg-amber-300 ring-4 ring-amber-300/20" /><div className="absolute left-[58%] top-[25%] h-3 w-3 rounded-full bg-emerald-300 ring-4 ring-emerald-300/20" /></div><div className="mt-3 flex flex-wrap gap-2 text-[11px] text-neutral-400">{zones.map((zone) => <span key={zone} className="rounded-full border border-white/10 px-2 py-1">{zone}</span>)}<span className="rounded-full border border-amber-300/30 px-2 py-1 text-amber-200">1 crane radius</span></div></div><div className="surface-shell px-5 py-4"><div className="flex items-center justify-between gap-3"><div><div className="text-[11px] font-medium tracking-[0.14em] text-neutral-400 uppercase">External Alerts Activity</div><div className="mt-2 text-lg font-medium text-neutral-100">Recent critical dispatches</div></div><a href="/settings/integrations" className="text-[11px] font-medium tracking-[0.12em] text-sky-300 uppercase no-underline">Open dispatcher</a></div><div className="mt-4 grid gap-2">{alerts.map((alert) => <div key={`${alert.time}-${alert.channel}`} className="flex items-center justify-between gap-3 border-b border-white/[0.06] py-2 last:border-0"><div className="min-w-0"><div className="truncate text-sm text-neutral-200">{alert.title}</div><div className="mt-1 text-[11px] font-mono tracking-[0.06em] text-neutral-500">{alert.time} · {alert.role}</div></div><span className={alert.channel === "SMS" ? "shrink-0 rounded-full bg-sky-500/10 px-2 py-1 text-[10px] font-medium text-sky-200" : "shrink-0 rounded-full bg-emerald-500/10 px-2 py-1 text-[10px] font-medium text-emerald-200"}>{alert.channel}</span></div>)}</div></div></section>;
}