"use client";

import { useState } from "react";
import { createProjectTask } from "@/app/lib/services";
import { RiskForecastCard } from "@/components/intelligence/RiskForecastCard";
import type { PredictiveRisk, ProjectScheduleTask } from "@/types/construction";

const risks: PredictiveRisk[] = [
  { id: "risk-1", title: "Quality rejection trend", category: "Quality", probability: .72, impact: 4, estimatedCostExposure: 18500000, signal: "WIR rejection rate 18%; cube break results are trending below the acceptance curve.", mitigation: "Increase pre-pour inspection and add a 7-day cube retest gate." },
  { id: "risk-2", title: "Weather-driven facade delay", category: "Weather", probability: .55, impact: 3, estimatedCostExposure: 9200000, signal: "Three severe weather alerts coincide with facade access windows.", mitigation: "Re-sequence sheltered facade zones and reserve an additional lift crew." },
  { id: "risk-3", title: "Aging design RFIs", category: "Schedule", probability: .81, impact: 4, estimatedCostExposure: 12400000, signal: "Open RFI aging exceeds 72 hours across two critical work packages.", mitigation: "Escalate unresolved RFIs to the design coordination gate." },
];

export default function RisksPage() { const [accepted, setAccepted] = useState<string[]>([]); const accept = async (risk: PredictiveRisk) => { const task: ProjectScheduleTask = { id: `mitigation-${risk.id}-${Date.now()}`, projectId: "proj-1", wbsCode: "RISK-MIT", title: `Mitigation: ${risk.title}`, discipline: "Civil", baselineStart: new Date().toISOString(), baselineFinish: new Date(Date.now() + 7 * 86400000).toISOString(), completionPercent: 0, criticalPath: risk.impact >= 4, status: "Not Started", earnedValue: 0, plannedValue: 0, actualCost: 0, createdAt: new Date().toISOString() }; await createProjectTask(task); setAccepted((current) => [...current, risk.id]); };
  return <main style={pageStyle}><div style={{ maxWidth: 1380, margin: "0 auto", display: "grid", gap: 22 }}><header><div style={eyebrow}>AI / Predictive Risk Intelligence</div><h1 style={heading}>Risk Forecast & Anomaly Dashboard</h1><p style={muted}>Leading indicators from WIR quality, cube breaks, weather alerts, and RFI aging.</p></header><section style={panel}><div style={eyebrow}>5 × 5 probability / impact matrix</div><div style={{ display: "grid", gridTemplateColumns: "repeat(5,1fr)", gap: 4, marginTop: 16 }}>{Array.from({ length: 25 }, (_, index) => { const impact = 5 - Math.floor(index / 5); const probability = (index % 5) + 1; const count = risks.filter((risk) => risk.impact === impact && Math.ceil(risk.probability * 5) === probability).length; const intensity = impact * probability; return <div key={index} title={`Probability ${probability}/5 · Impact ${impact}/5`} style={{ minHeight: 54, display: "grid", placeItems: "center", background: intensity >= 16 ? "#991b1b" : intensity >= 9 ? "#a16207" : "#155e75", borderRadius: 5, color: "#fff", fontWeight: 800 }}>{count || ""}</div>; })}</div><div style={{ display: "flex", justifyContent: "space-between", color: "#94a3b8", fontSize: 12, marginTop: 8 }}><span>Low probability</span><span>High probability</span></div></section><section style={grid}>{risks.map((risk) => <RiskForecastCard key={risk.id} risk={risk} onAccept={() => void accept(risk)} />)}</section>{accepted.length > 0 && <div style={{ color: "#86efac", fontWeight: 700 }}>{accepted.length} mitigation task(s) created in the project schedule.</div>}</div></main>; }
const pageStyle = { minHeight: "100vh", background: "#050816", color: "#e2e8f0", padding: "32px 24px 64px" }; const heading = { margin: "8px 0 0", fontSize: 42 }; const eyebrow = { color: "#7dd3fc", fontSize: 11, letterSpacing: ".16em", textTransform: "uppercase" as const }; const muted = { color: "#94a3b8", lineHeight: 1.5 }; const panel = { background: "rgba(15,23,42,.82)", border: "1px solid rgba(148,163,184,.2)", borderRadius: 18, padding: 20 }; const grid = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(280px,1fr))", gap: 16 };
