"use client";

import React, { useState, useEffect } from "react";

export interface DigitalAuditFooterProps {
  timestampUtc?: string;
  transactionHash?: string;
  signatoryRole?: string;
  clientIpProtocol?: string;
  className?: string;
}

export const DigitalAuditFooter: React.FC<DigitalAuditFooterProps> = ({
  timestampUtc,
  transactionHash = "0x8f4c2e1b9a7d3f5e6c8b0a2d4f6e8a1c3e5b7d9f1a3c5e7b9d1f3a5c7e9b1d3f",
  signatoryRole = "Authorised Signatory [Architect / Client CoA/CIN]",
  clientIpProtocol = "Client IP Protocol: 192.168.1.104 [TLS 1.3 / HSM-SECP256K1]",
  className = "",
}) => {
  const [timestamp, setTimestamp] = useState<string>(
    timestampUtc || "2026-09-19T12:00:00.000Z"
  );

  useEffect(() => {
    if (!timestampUtc) {
      setTimestamp(new Date().toISOString());
    }
  }, [timestampUtc]);

  return (
    <footer
      data-audit-footer
      className={`hidden print:flex flex-col w-full pt-6 mt-auto border-t-2 border-black text-[10px] uppercase font-mono text-black digital-audit-footer ${className}`}
      style={{ breakInside: "avoid", pageBreakInside: "avoid" }}
    >
      <div className="grid grid-cols-3 gap-6 items-end w-full">
        {/* Left Column */}
        <div className="flex flex-col space-y-1 text-left">
          <span className="font-bold">
            Digitally Generated By: Quadillar LiveView QMS
          </span>
          <span>Timestamp: {timestamp} (UTC)</span>
          <span className="text-[9px] text-zinc-600 print:text-black">
            Statutory Compliance: CPWD Works Manual 2024
          </span>
        </div>

        {/* Center Column */}
        <div className="flex flex-col space-y-1 text-center">
          <span className="font-bold">{clientIpProtocol}</span>
          <span className="break-all font-mono">
            SHA-256: {transactionHash}
          </span>
          <span className="text-[9px] text-zinc-600 print:text-black">
            Zero-Trust Cryptographic Ledger Verification
          </span>
        </div>

        {/* Right Column */}
        <div className="flex flex-col space-y-2 text-right">
          <div className="h-8 border-b border-black w-48 ml-auto" />
          <span className="font-bold">{signatoryRole}</span>
          <span className="text-[9px] text-zinc-600 print:text-black">
            Physical Countersignature & Official Stamp
          </span>
        </div>
      </div>
    </footer>
  );
};

export default DigitalAuditFooter;
