"use client";

import { useMemo, useState } from "react";
import { createPunchListFromAssetDefect } from "@/app/lib/services";
import type { FacilityAssetRecord, PreventiveMaintenanceStatus, WarrantyStatus } from "@/types/construction";

function badge(status: WarrantyStatus | PreventiveMaintenanceStatus) {
  const color = status === "Active Warranty" || status === "Healthy" ? "#bbf7d0" : status === "Expiring in < 30 Days" || status === "PM Due in < 15 Days" ? "#fde68a" : "#fecaca";
  const background = status === "Active Warranty" || status === "Healthy" ? "rgba(34,197,94,.12)" : status === "Expiring in < 30 Days" || status === "PM Due in < 15 Days" ? "rgba(245,158,11,.12)" : "rgba(239,68,68,.12)";
  return { display: "inline-block", borderRadius: 999, padding: "6px 9px", fontSize: 11, color, background };
}

export function AssetRegisterTable({ initialAssets }: { initialAssets: FacilityAssetRecord[] }) {
  const [assets, setAssets] = useState(initialAssets);
  const [selected, setSelected] = useState<FacilityAssetRecord | null>(null);
  const today = Date.now();
  const warrantyStatus = (asset: FacilityAssetRecord): WarrantyStatus => { const days = Math.ceil((new Date(asset.warrantyEndDate).getTime() - today) / 86400000); return days < 0 ? "Expired / Out of Warranty" : days < 30 ? "Expiring in < 30 Days" : "Active Warranty"; };
  const pmStatus = (asset: FacilityAssetRecord): PreventiveMaintenanceStatus => { const due = new Date(asset.pmDueDate ?? new Date(today + 20 * 86400000)).getTime(); const days = Math.ceil((due - today) / 86400000); return days < 0 ? "PM Overdue" : days < 15 ? "PM Due in < 15 Days" : "Healthy"; };
  const counts = useMemo(() => ({ commissioned: assets.filter((asset) => asset.commissioned).length, documents: assets.filter((asset) => asset.omManualUrl).length, active: assets.filter((asset) => warrantyStatus(asset) === "Active Warranty").length }), [assets]);
  const claim = async (asset: FacilityAssetRecord) => { await createPunchListFromAssetDefect(asset); setAssets((current) => current.map((item) => item.id === asset.id ? { ...item, defectDescription: `${item.defectDescription ?? "Warranty defect"} (Claim initiated)` } : item)); };
  const exportCertificate = () => { const lines = assets.map((asset) => `${asset.assetTag} | ${asset.assetName} | Serial ${asset.serialNumber} | Warranty ends ${asset.warrantyEndDate} | O&M ${asset.omManualUrl ? "available" : "missing"} | Inspections ${asset.inspectionLogs?.length ?? 0}`); const body = lines.map((line, index) => `BT /F1 10 Tf 40 ${760 - index * 14} Td (${line.replace(/[\\()]/g, "\\$&")}) Tj ET`).join("\n"); const pdf = `%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>endobj\n4 0 obj<</Length ${body.length}>>stream\n${body}\nendstream\nendobj\n5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\ntrailer<</Root 1 0 R>>\n%%EOF`; const url = URL.createObjectURL(new Blob([pdf], { type: "application/pdf" })); const link = document.createElement("a"); link.href = url; link.download = "quadillar-digital-handover-certificate.pdf"; link.click(); URL.revokeObjectURL(url); };

  return <div style={{ display: "grid", gap: 18 }}><div style={topBar}><div style={summaryGrid}>{[["Assets", assets.length], ["Commissioned", `${counts.commissioned}/${assets.length}`], ["O&M manuals", `${counts.documents}/${assets.length}`], ["Active warranties", counts.active]].map(([label, value]) => <div key={String(label)} style={summaryCard}><div style={eyebrow}>{label}</div><div style={summaryValue}>{value}</div></div>)}</div><button type="button" onClick={exportCertificate} style={button}>Generate digital handover certificate PDF</button></div><div style={tableWrap}><table style={table}><thead><tr>{["Asset tag", "Asset / category", "Serial", "Commissioned", "Vendor", "Warranty", "Preventive maintenance", "Documents", "Action"].map((heading) => <th key={heading} style={th}>{heading}</th>)}</tr></thead><tbody>{assets.map((asset) => { const warranty = warrantyStatus(asset); const pm = pmStatus(asset); return <tr key={asset.id}><td style={td}><strong>{asset.assetTag}</strong></td><td style={td}><strong>{asset.assetName}</strong><div style={muted}>{asset.category}</div></td><td style={td}>{asset.serialNumber}</td><td style={td}>{asset.commissioned ? "Yes" : "Pending"}</td><td style={td}>{asset.vendorName}<div style={muted}>{asset.vendorContact}</div></td><td style={td}><span style={badge(warranty)}>{warranty}</span><div style={muted}>Ends {asset.warrantyEndDate}</div></td><td style={td}><span className={pm === "PM Overdue" ? "animate-pulse" : undefined} style={badge(pm)}>{pm}</span><div style={muted}>Due {asset.pmDueDate ?? "Next planned cycle"}</div></td><td style={td}><div style={{ display: "flex", gap: 8 }}>{asset.asBuiltDrawingUrl && <a href={asset.asBuiltDrawingUrl} target="_blank" rel="noreferrer" style={link}>As-built</a>}{asset.omManualUrl && <a href={asset.omManualUrl} target="_blank" rel="noreferrer" style={link}>O&M</a>}{asset.warrantyCardUrl && <a href={asset.warrantyCardUrl} target="_blank" rel="noreferrer" style={link}>Warranty</a>}</div></td><td style={td}><button type="button" onClick={() => setSelected(asset)} style={button}>Details</button>{asset.defectDescription && <button type="button" onClick={() => void claim(asset)} style={{ ...button, marginLeft: 7, color: "#fca5a5" }}>Claim</button>}</td></tr>; })}</tbody></table></div>{selected && <div style={overlay} onClick={() => setSelected(null)}><div style={modal} onClick={(event) => event.stopPropagation()}><div style={{ display: "flex", justifyContent: "space-between" }}><div><div style={eyebrow}>Facility asset</div><h2 style={{ margin: "6px 0 0" }}>{selected.assetTag} · {selected.assetName}</h2></div><button type="button" onClick={() => setSelected(null)} style={close}>×</button></div><div style={{ color: "#cbd5e1", lineHeight: 1.7 }}>Vendor: {selected.vendorName}<br />Serial: {selected.serialNumber}<br />Warranty: {selected.warrantyStartDate} to {selected.warrantyEndDate}<br />Inspection logs: {selected.inspectionLogs?.length ?? 0}</div></div></div>}</div>;
}

const topBar: React.CSSProperties = { display: "flex", alignItems: "center", gap: 16, flexWrap: "wrap" }; const summaryGrid: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: 14, flex: 1 }; const summaryCard: React.CSSProperties = { background: "#111827", border: "1px solid #1e293b", borderRadius: 14, padding: 14 }; const eyebrow: React.CSSProperties = { color: "#94a3b8", fontSize: 10, letterSpacing: ".14em", textTransform: "uppercase" }; const summaryValue: React.CSSProperties = { marginTop: 9, color: "#f8fafc", fontSize: 24, fontWeight: 900 }; const button: React.CSSProperties = { border: "1px solid #334155", borderRadius: 9, background: "transparent", color: "#cbd5e1", padding: "9px 11px", cursor: "pointer", fontSize: 11, fontWeight: 800 }; const tableWrap: React.CSSProperties = { overflowX: "auto", border: "1px solid #1e293b", borderRadius: 16 }; const table: React.CSSProperties = { width: "100%", minWidth: 1250, borderCollapse: "collapse" }; const th: React.CSSProperties = { padding: 13, textAlign: "left", color: "#94a3b8", fontSize: 10, textTransform: "uppercase", borderBottom: "1px solid #1e293b" }; const td: React.CSSProperties = { padding: 13, color: "#cbd5e1", fontSize: 13, borderBottom: "1px solid rgba(148,163,184,.1)", verticalAlign: "top" }; const muted: React.CSSProperties = { marginTop: 4, color: "#94a3b8", fontSize: 11 }; const link: React.CSSProperties = { color: "#7dd3fc", fontSize: 11 }; const overlay: React.CSSProperties = { position: "fixed", inset: 0, zIndex: 100, display: "grid", placeItems: "center", padding: 20, background: "rgba(2,6,23,.8)" }; const modal: React.CSSProperties = { width: "min(580px, 100%)", background: "#0b1220", border: "1px solid #334155", borderRadius: 18, padding: 22, color: "#e2e8f0" }; const close: React.CSSProperties = { width: 34, height: 34, borderRadius: 8, border: "1px solid #334155", background: "transparent", color: "#f8fafc", cursor: "pointer", fontSize: 20 };
