"use client";

import { useState } from "react";
import type { CustomerPossessionRecord, PossessionChecklistKey } from "@/types/construction";

const checks: PossessionChecklistKey[] = ["Finishes", "Plumbing fixtures", "Electrical switches", "Utility meters"];
export function CustomerHandoverModal({ record, onClose, onUpdated }: { record: CustomerPossessionRecord | null; onClose: () => void; onUpdated: (record: CustomerPossessionRecord) => void }) {
  const [draft, setDraft] = useState(record); const [buyerSigned, setBuyerSigned] = useState(false); const [managerSigned, setManagerSigned] = useState(false);
  if (!draft) return null;
  const clear = draft.unresolvedSnagsCount === 0; const certify = () => { if (clear && buyerSigned && managerSigned) onUpdated({ ...draft, handedOver: true }); };
  const printSlip = () => { const popup = window.open("", "_blank"); if (!popup) return; popup.document.write(`<html><body style="font-family:Arial;padding:40px"><h1>Formal Possession Letter & Key Handover Slip</h1><p>Unit: ${draft.unitRef} / Buyer: ${draft.buyerName}</p><p>All walkthrough controls certified: ${clear ? "YES" : "NO"}</p><p>Pending rectification tickets: ${draft.pendingTickets.join(", ") || "None"}</p><p>Buyer digital sign-off: ${buyerSigned ? "Verified" : "Pending"}</p><p>Site manager digital sign-off: ${managerSigned ? "Verified" : "Pending"}</p><p>Keys delivered: ${draft.handedOver ? "YES" : "Pending certification"}</p></body></html>`); popup.document.close(); popup.print(); };
  return <div style={overlay}><div style={modal}><div style={header}><div><div style={eyebrow}>Customer handover / zero-defect gate</div><h2 style={{ margin: "6px 0 0", fontSize: 24 }}>{draft.unitRef} · {draft.buyerName}</h2></div><button type="button" onClick={onClose} style={close} aria-label="Close handover modal">×</button></div><div style={checksBox}>{checks.map((key) => <label key={key}><input type="checkbox" checked={draft.checklist[key]} onChange={(event) => setDraft({ ...draft, checklist: { ...draft.checklist, [key]: event.target.checked } })} /> {key}</label>)}</div><div style={{ ...snagBox, borderColor: clear ? "#166534" : "#991b1b" }}><strong>{clear ? "Zero-defect gate clear" : `${draft.unresolvedSnagsCount} unresolved snags block possession`}</strong>{!clear && <div style={small}>Pending rectification: {draft.pendingTickets.join(", ")}</div>}</div>{clear && <div style={signBox}><div style={eyebrow}>Digital stylus sign-off</div><label><input type="checkbox" checked={buyerSigned} onChange={(event) => setBuyerSigned(event.target.checked)} /> Buyer signature captured</label><label><input type="checkbox" checked={managerSigned} onChange={(event) => setManagerSigned(event.target.checked)} /> Site manager signature captured</label></div>}<div style={actions}><button type="button" onClick={printSlip} style={secondary}>Generate Formal Possession Letter & Key Handover Slip</button><button type="button" disabled={!clear || !buyerSigned || !managerSigned} onClick={certify} style={{ ...primary, opacity: clear && buyerSigned && managerSigned ? 1 : .45 }}>Certify Possession</button></div></div></div>;
}
const overlay = { position: "fixed" as const, inset: 0, zIndex: 100, display: "grid", placeItems: "center", padding: 20, background: "rgba(2,6,23,.82)" }; const modal = { width: "min(700px,100%)", background: "#0b1220", border: "1px solid #334155", borderRadius: 20, padding: 24, color: "#e2e8f0", display: "grid", gap: 18 }; const header = { display: "flex", justifyContent: "space-between", alignItems: "flex-start" }; const eyebrow = { color: "#7dd3fc", fontSize: 11, letterSpacing: ".14em", textTransform: "uppercase" as const }; const close = { width: 34, height: 34, borderRadius: 999, border: "1px solid #334155", background: "transparent", color: "#f8fafc", cursor: "pointer", fontSize: 20 }; const checksBox = { display: "grid", gap: 10, background: "#111827", borderRadius: 10, padding: 15 }; const snagBox = { border: "1px solid", borderRadius: 10, padding: 14, color: "#f8fafc" }; const signBox = { display: "grid", gap: 10, background: "rgba(34,197,94,.08)", border: "1px solid rgba(34,197,94,.35)", borderRadius: 10, padding: 15 }; const small = { color: "#fca5a5", fontSize: 12, marginTop: 6 }; const actions = { display: "flex", justifyContent: "flex-end", gap: 10, flexWrap: "wrap" as const }; const primary = { border: 0, borderRadius: 9, background: "#22c55e", color: "#052e16", padding: "10px 14px", fontWeight: 800, cursor: "pointer" }; const secondary = { border: "1px solid #334155", borderRadius: 9, background: "transparent", color: "#cbd5e1", padding: "10px 14px", cursor: "pointer" };
