"use client";

import { useState } from "react";
import type { FinalSettlement, SettlementStatus } from "@/types/construction";

export function FinalSettlementModal({ settlement, onClose, onSave }: { settlement: FinalSettlement | null; onClose: () => void; onSave: (settlement: FinalSettlement) => void }) {
  const [draft, setDraft] = useState(settlement);
  if (!settlement || !draft) return null;
  const update = <K extends keyof FinalSettlement>(key: K, value: FinalSettlement[K]) => setDraft((current) => current ? { ...current, [key]: value } : current);
  const dlpExpired = new Date(draft.dlpExpiry).getTime() <= Date.now();
  const canSettle = draft.punchItemsClosed && Boolean(draft.noClaimsCertificate) && Boolean(draft.finalCompletionCertificate) && dlpExpired;
  return <div style={overlay}><div style={modal}><div style={{ display: "flex", justifyContent: "space-between" }}><div><div style={eyebrow}>Final account review</div><h2 style={{ margin: "8px 0 0" }}>{draft.packageName}</h2></div><button type="button" onClick={onClose} style={close}>×</button></div><div style={{ display: "grid", gap: 14, marginTop: 20 }}><label>Engineer / commercial determination<textarea value={draft.status} onChange={(event) => update("status", event.target.value as SettlementStatus)} rows={2} style={input} /></label><label>Defect Liability Period expiry<input type="date" value={draft.dlpExpiry} onChange={(event) => update("dlpExpiry", event.target.value)} style={input} /></label><label>No-Claims Certificate<input type="file" accept="application/pdf,image/*" onChange={(event) => update("noClaimsCertificate", event.target.files?.[0]?.name)} style={input} /></label><label>Final Completion Certificate<input type="file" accept="application/pdf,image/*" onChange={(event) => update("finalCompletionCertificate", event.target.files?.[0]?.name)} style={input} /></label><div style={{ color: canSettle ? "#86efac" : "#fbbf24", fontWeight: 700 }}>{canSettle ? "All controls passed. 100% retention release is eligible." : "Settlement blocked until punch closure, certificates, and DLP expiry are complete."}</div></div><div style={{ display: "flex", justifyContent: "end", gap: 10, marginTop: 20 }}><button type="button" onClick={() => onSave({ ...draft, status: canSettle ? "Settled & Closed" : "In Review", retentionAmount: canSettle ? 0 : draft.retentionAmount })} style={button}>Save closeout</button></div></div></div>;
}
const overlay = { position: "fixed" as const, inset: 0, zIndex: 100, display: "grid", placeItems: "center", padding: 20, background: "rgba(2,6,23,.82)" }; const modal = { width: "min(600px,100%)", background: "#0f172a", color: "#e2e8f0", border: "1px solid rgba(148,163,184,.25)", borderRadius: 18, padding: 22 }; const eyebrow = { color: "#7dd3fc", fontSize: 11, letterSpacing: ".16em", textTransform: "uppercase" as const }; const close = { border: 0, background: "transparent", color: "#cbd5e1", fontSize: 24, cursor: "pointer" }; const input = { display: "block", width: "100%", boxSizing: "border-box" as const, marginTop: 6, background: "#020817", color: "#f8fafc", border: "1px solid rgba(148,163,184,.25)", borderRadius: 9, padding: "10px" }; const button = { border: "1px solid rgba(52,211,153,.4)", background: "rgba(52,211,153,.12)", color: "#ecfdf5", borderRadius: 9, padding: "10px 16px", fontWeight: 800, cursor: "pointer" };
