"use client";

import { useState } from "react";
import type { SubcontractorWorkOrder } from "@/types/construction";

export function WorkOrderDetailModal({ order, onClose, onSave }: { order: SubcontractorWorkOrder; onClose: () => void; onSave: (order: SubcontractorWorkOrder) => void }) {
  const [record, setRecord] = useState(order);
  const [rebuttal, setRebuttal] = useState("");
  const retainage = record.cumulativeClaimed * record.retainageRate / 100;
  const payable = Math.max(0, record.cumulativeClaimed - retainage);
  const authorized = record.masterIpcFunded;
  const exportAdvice = () => { const lines = record.lineItems.map((item) => `${item.description}: INR ${item.amount.toLocaleString("en-IN")}`); const content = ["SUBCONTRACTOR PAYMENT ADVICE", `Work Order: ${record.workOrderNumber}`, `Subcontractor: ${record.subcontractor}`, `Milestone: ${record.milestone}`, "", ...lines, "", `Claimed: INR ${record.cumulativeClaimed.toLocaleString("en-IN")}`, `Retainage: INR ${retainage.toLocaleString("en-IN")}`, `Net payable: INR ${payable.toLocaleString("en-IN")}`, `Master IPC funded: ${authorized ? "Yes" : "No"}`].join("\n"); const printWindow = window.open("", "_blank"); if (!printWindow) return; printWindow.document.write(`<html><body style="font-family:Arial;padding:48px;white-space:pre-wrap">${content}</body></html>`); printWindow.document.close(); printWindow.print(); };
  return <div style={overlay} role="dialog" aria-modal="true" aria-label="Work order detail modal"><div style={modal}><header style={header}><div><div style={eyebrow}>Back-to-back billing · {record.workOrderNumber}</div><h2 style={{ margin: "7px 0 0", fontSize: 23 }}>{record.tradePackage}</h2><div style={muted}>{record.subcontractor} · {record.milestone}</div></div><button type="button" onClick={onClose} style={close}>×</button></header><section style={metrics}><div><span>Contract value</span><strong>₹{record.contractValue.toLocaleString("en-IN")}</strong></div><div><span>Claimed to date</span><strong>₹{record.cumulativeClaimed.toLocaleString("en-IN")}</strong></div><div><span>Retainage / net</span><strong>₹{retainage.toLocaleString("en-IN")} / ₹{payable.toLocaleString("en-IN")}</strong></div></section><div style={gateStyle}><strong>{authorized ? "Master IPC funded / disbursed" : "Pay-when-paid hold"}</strong><span>{authorized ? "Subcontractor payment authorization is available." : "Authorization is locked until the corresponding client IPC is funded."}</span></div><div style={actions}><button type="button" onClick={exportAdvice} style={secondary}>Generate payment advice</button><button type="button" disabled={!authorized} onClick={() => onSave({ ...record, status: "Disbursed" })} style={{ ...primary, opacity: authorized ? 1 : .45 }}>Authorize subcontractor payment</button></div></div></div>;
}
const overlay: React.CSSProperties = { position: "fixed", inset: 0, zIndex: 70, display: "grid", placeItems: "center", padding: 20, background: "rgba(2,6,23,.82)" }; const modal: React.CSSProperties = { width: "min(720px, 100%)", background: "#0b1220", border: "1px solid #334155", borderRadius: 16, padding: 22, color: "#e2e8f0" }; const header: React.CSSProperties = { display: "flex", justifyContent: "space-between", alignItems: "flex-start" }; const eyebrow: React.CSSProperties = { color: "#67e8f9", fontSize: 10, letterSpacing: ".15em", textTransform: "uppercase", fontWeight: 800 }; const muted: React.CSSProperties = { color: "#94a3b8", fontSize: 12, marginTop: 5 }; const close: React.CSSProperties = { width: 34, height: 34, borderRadius: 8, border: "1px solid #334155", background: "transparent", color: "#f8fafc", fontSize: 20, cursor: "pointer" }; const metrics: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 10, marginTop: 20 }; const gateStyle: React.CSSProperties = { display: "grid", gap: 5, marginTop: 16, padding: 13, border: "1px solid #92400e", borderRadius: 9, background: "#451a0333", color: "#fcd34d", fontSize: 12 }; const actions: React.CSSProperties = { display: "flex", justifyContent: "flex-end", gap: 10, flexWrap: "wrap", marginTop: 20 }; const primary: React.CSSProperties = { border: 0, borderRadius: 8, background: "#34d399", color: "#052e16", padding: "10px 12px", fontWeight: 900, cursor: "pointer" }; const secondary: React.CSSProperties = { border: "1px solid #334155", borderRadius: 8, background: "transparent", color: "#cbd5e1", padding: "10px 12px", cursor: "pointer" };