import type { PhaseInspectionGate } from "@/types/construction";

export const defaultPhaseGates: PhaseInspectionGate[] = [
  {
    id: "phase-1",
    projectId: "GOMTI-NAGAR-PH1-FITOUT",
    phaseNumber: 1,
    phaseName: "Site Preparation",
    mandatoryInspection: "Survey and earthworks readiness",
    inspectionPassStatus: true,
    isClosed: false,
    isMandatory: true,
  },
  {
    id: "phase-2",
    projectId: "GOMTI-NAGAR-PH1-FITOUT",
    phaseNumber: 2,
    phaseName: "Foundation",
    mandatoryInspection: "Pile / footing inspection",
    inspectionPassStatus: false,
    isClosed: false,
    isMandatory: true,
  },
  {
    id: "phase-3",
    projectId: "GOMTI-NAGAR-PH1-FITOUT",
    phaseNumber: 3,
    phaseName: "Structural Frame",
    mandatoryInspection: "Concrete cover and reinforcement checks",
    inspectionPassStatus: true,
    isClosed: false,
    isMandatory: true,
  },
  {
    id: "phase-4",
    projectId: "GOMTI-NAGAR-PH1-FITOUT",
    phaseNumber: 4,
    phaseName: "Envelope",
    mandatoryInspection: "Facade and waterproofing inspection",
    inspectionPassStatus: true,
    isClosed: false,
    isMandatory: true,
  },
  {
    id: "phase-5",
    projectId: "GOMTI-NAGAR-PH1-FITOUT",
    phaseNumber: 5,
    phaseName: "MEP Rough-in",
    mandatoryInspection: "MEP coordination and pressure test",
    inspectionPassStatus: true,
    isClosed: false,
    isMandatory: true,
  },
  {
    id: "phase-6",
    projectId: "GOMTI-NAGAR-PH1-FITOUT",
    phaseName: "Finishes",
    phaseNumber: 6,
    mandatoryInspection: "Surface and finish approval",
    inspectionPassStatus: true,
    isClosed: false,
    isMandatory: false,
  },
  {
    id: "phase-7",
    projectId: "GOMTI-NAGAR-PH1-FITOUT",
    phaseNumber: 7,
    phaseName: "Testing & Commissioning",
    mandatoryInspection: "Integrated system commissioning",
    inspectionPassStatus: false,
    isClosed: false,
    isMandatory: true,
  },
  {
    id: "phase-8",
    projectId: "GOMTI-NAGAR-PH1-FITOUT",
    phaseNumber: 8,
    phaseName: "Handover",
    mandatoryInspection: "Defects and snag closure",
    inspectionPassStatus: true,
    isClosed: false,
    isMandatory: true,
  },
];
