"use client";

import { useState } from "react";
import type { DrawingRedlineAnnotation, RedlineRole, RedlineTool } from "@/types/construction";

const roleColors: Record<RedlineRole, string> = { Architect: "#e11d48", "Structural Engineer": "#2563eb", "MEP Consultant": "#10b981", "General Contractor": "#f59e0b" };
const tools: RedlineTool[] = ["Revision Cloud", "Leader Arrow", "Freehand Pen", "Highlighter", "Dimension Caliper", "Official Stamp"];

export function DrawingRedlineCanvas() {
  const [tool, setTool] = useState<RedlineTool>("Revision Cloud");
  const [role, setRole] = useState<RedlineRole>("Architect");
  const [stamp, setStamp] = useState<DrawingRedlineAnnotation["stampText"]>("GFC APPROVED");
  const [annotations, setAnnotations] = useState<DrawingRedlineAnnotation[]>([{ id: "redline-01", projectId: "proj-1", tool: "Revision Cloud", role: "Architect", label: "Revise beam opening detail", points: [{ x: 23, y: 25 }, { x: 42, y: 25 }, { x: 42, y: 38 }, { x: 23, y: 38 }], resolved: false }]);
  const active = annotations.filter((annotation) => !annotation.resolved).length;
  const addMarkup = (event: React.MouseEvent<SVGSVGElement>) => { const rect = event.currentTarget.getBoundingClientRect(); const x = ((event.clientX - rect.left) / rect.width) * 100; const y = ((event.clientY - rect.top) / rect.height) * 100; const label = tool === "Official Stamp" ? stamp || "GFC APPROVED" : tool; setAnnotations((current) => [...current, { id: `redline-${Date.now()}`, projectId: "proj-1", tool, role, label, points: [{ x, y }, { x: x + 13, y }, { x: x + 13, y: y + 9 }, { x, y: y + 9 }], stampText: tool === "Official Stamp" ? stamp : undefined, resolved: false }]); };
  const resolve = (id: string) => setAnnotations((current) => current.map((annotation) => annotation.id === id ? { ...annotation, resolved: true, resolvedAt: new Date().toISOString() } : annotation));
  return <section style={panel}><div style={toolbar}><div><div style={eyebrow}>CDE / controlled markup</div><h2 style={title}>2D drawing redline review</h2></div><div style={controls}><select value={role} onChange={(event) => setRole(event.target.value as RedlineRole)} style={input}>{Object.keys(roleColors).map((value) => <option key={value}>{value}</option>)}</select>{tools.map((value) => <button key={value} type="button" onClick={() => setTool(value)} style={{ ...toolButton, background: tool === value ? roleColors[role] : "#111827", color: tool === value ? "#fff" : "#cbd5e1" }}>{value}</button>)}</div></div>{tool === "Official Stamp" && <select value={stamp} onChange={(event) => setStamp(event.target.value as DrawingRedlineAnnotation["stampText"])} style={{ ...input, marginTop: 12, maxWidth: 240 }}><option>GFC APPROVED</option><option>SUPERSEDED</option><option>WORK IN PROGRESS</option></select>}<svg viewBox="0 0 100 60" onClick={addMarkup} style={canvas} role="img" aria-label="Interactive vector drawing redline canvas"><defs><pattern id="grid" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M 5 0 L 0 0 0 5" fill="none" stroke="#334155" strokeWidth=".12" /></pattern><marker id="arrow" markerWidth="4" markerHeight="4" refX="3" refY="2" orient="auto"><path d="M0,0 L4,2 L0,4 z" fill="#e11d48" /></marker></defs><rect width="100" height="60" fill="#e2e8f0" /><rect width="100" height="60" fill="url(#grid)" /><rect x="8" y="8" width="84" height="44" fill="none" stroke="#475569" strokeWidth=".35" /><rect x="15" y="14" width="25" height="17" fill="none" stroke="#0f172a" strokeWidth=".45" /><rect x="52" y="18" width="29" height="22" fill="none" stroke="#0f172a" strokeWidth=".45" /><text x="10" y="56" fontSize="2.5" fill="#475569">GFC / STRUCTURAL LAYOUT / REV 03</text>{annotations.map((annotation) => <g key={annotation.id} opacity={annotation.resolved ? .3 : 1}><polygon points={annotation.points.map((point) => `${point.x},${point.y}`).join(" ")} fill={annotation.tool === "Highlighter" ? `${roleColors[annotation.role]}44` : "none"} stroke={roleColors[annotation.role]} strokeWidth={annotation.tool === "Highlighter" ? 2 : .7} strokeDasharray={annotation.tool === "Revision Cloud" ? "1.2 1" : undefined} />{annotation.tool === "Leader Arrow" && <line x1={annotation.points[0].x} y1={annotation.points[0].y} x2={annotation.points[1].x + 10} y2={annotation.points[1].y + 6} stroke={roleColors[annotation.role]} strokeWidth=".7" markerEnd="url(#arrow)" />}<text x={annotation.points[0].x} y={annotation.points[0].y - 1} fontSize="2.2" fill={roleColors[annotation.role]}>{annotation.label}</text></g>)}</svg><div style={footer}><span style={{ color: active ? "#fcd34d" : "#86efac" }}>{active} unresolved markups</span>{annotations.filter((annotation) => !annotation.resolved).map((annotation) => <button key={annotation.id} type="button" onClick={() => resolve(annotation.id)} style={resolveButton}>Resolve in Rev 1 · audit timestamp</button>)}</div></section>;
}

const panel: React.CSSProperties = { background: "#0b1220", border: "1px solid #1e293b", borderRadius: 16, padding: 20 }; const toolbar: React.CSSProperties = { display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 14, flexWrap: "wrap" }; const eyebrow: React.CSSProperties = { color: "#67e8f9", fontSize: 10, letterSpacing: ".15em", textTransform: "uppercase", fontWeight: 800 }; const title: React.CSSProperties = { margin: "7px 0 0", fontSize: 22 }; const controls: React.CSSProperties = { display: "flex", gap: 7, flexWrap: "wrap", justifyContent: "flex-end" }; const input: React.CSSProperties = { background: "#111827", color: "#f8fafc", border: "1px solid #334155", borderRadius: 7, padding: 8, fontSize: 11 }; const toolButton: React.CSSProperties = { border: "1px solid #334155", borderRadius: 7, padding: "8px 9px", fontSize: 10, cursor: "pointer" }; const canvas: React.CSSProperties = { display: "block", width: "100%", height: "auto", minHeight: 420, marginTop: 16, border: "1px solid #334155", cursor: "crosshair" }; const footer: React.CSSProperties = { display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap", marginTop: 14, fontSize: 12 }; const resolveButton: React.CSSProperties = { border: "1px solid #334155", borderRadius: 7, background: "#111827", color: "#cbd5e1", padding: "7px 9px", cursor: "pointer" };
