"use client";

import { useState } from "react";
import type { SiteDailyProgressReport } from "@/types/construction";
import { openDprReportPrint } from "@/lib/reports/generateDPRPdf";

const draftReport: SiteDailyProgressReport = { id: "dpr-auto-today", projectId: "proj-1", reportDate: new Date().toISOString(), weather: { condition: "Partly Cloudy", temperatureC: 30, humidityPct: 60, windKph: 14 }, manpower: { total: 88, subcontractors: 70, supervisors: 8 }, machinery: { active: 12, breakdown: [] }, narrative: "Automatically compiled from today's field telemetry, labor attendance, equipment logs, concrete records, and safety register.", milestoneLogs: [{ title: "Structural frame", status: "Completed", note: "Level 03 slab pour completed." }, { title: "MEP rough-in", status: "In Progress", note: "North wing routing continues." }], photos: [], status: "Draft", createdAt: new Date().toISOString() };

export function DPRComposer({ onCompiled }: { onCompiled?: (report: SiteDailyProgressReport) => void }) { const [report, setReport] = useState<SiteDailyProgressReport | null>(null); const [stamps, setStamps] = useState({ contractor: false, consultant: false, client: false }); const compile = () => { setReport({ ...draftReport, reportDate: new Date().toISOString(), createdAt: new Date().toISOString() }); onCompiled?.(draftReport); }; const approve = (key: keyof typeof stamps) => setStamps((current) => ({ ...current, [key]: true })); const status = stamps.client ? "Fully Signed" : stamps.consultant ? "Pending Client Final Approval" : stamps.contractor ? "Pending Consultant Sign-off" : "Drafting"; const exportPdf = () => { if (!report) return; void openDprReportPrint({ projectName: "Project 01 / Core Shell", projectCode: "QL-CORE-01", dateLabel: new Date(report.reportDate).toLocaleDateString("en-IN", { dateStyle: "medium" }), weatherSummary: `${report.weather.condition}, ${report.weather.temperatureC}°C, ${report.weather.humidityPct}% RH, ${report.weather.windKph} kph`, manpowerSummary: `${report.manpower.total} total / ${report.manpower.subcontractors} subcontractors / ${report.manpower.supervisors} supervisors`, machinerySummary: `${report.machinery.active} active; ${report.machinery.breakdown.join(" | ") || "No breakdown"}`, narrative: report.narrative, milestoneLogs: report.milestoneLogs, photos: [] }); };
  return <section style={{ display: "grid", gap: 18, background: "#0b1220", border: "1px solid #1e293b", borderRadius: 20, padding: 20 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 12, alignItems: "center", flexWrap: "wrap" }}><div><div style={eyebrow}>Automated DPR aggregation engine</div><h2 style={{ margin: "8px 0 0", fontSize: 26 }}>Today's field report</h2></div><button type="button" onClick={compile} style={button}>Auto-Compile Today's DPR</button></div>{report && <><div style={{ color: stamps.client ? "#86efac" : "#fbbf24", fontWeight: 800 }}>Status: {status}</div><div style={grid}><div style={card}><small>Weather</small><strong>{report.weather.condition} · {report.weather.temperatureC}°C</strong><span>{report.weather.humidityPct}% RH · {report.weather.windKph} kph</span></div><div style={card}><small>Headcount by trade</small><strong>{report.manpower.total} active workers</strong><span>Masons 22 · Steel 20 · Carpenters 14 · Helpers 32</span></div><div style={card}><small>Heavy machinery deployed</small><strong>{report.machinery.active} active units</strong><span>{report.machinery.breakdown.length ? report.machinery.breakdown.join(", ") : "No breakdowns"}</span></div><div style={card}><small>Site photos gallery</small><strong>{report.photos.length || 0} photos attached</strong><span>Ready for field photo append</span></div></div><div style={card}><small>Key milestones achieved</small>{report.milestoneLogs.map((item) => <div key={item.title} style={{ display: "flex", justifyContent: "space-between", gap: 10, marginTop: 10 }}><span>{item.title}</span><span style={{ color: item.status === "Completed" ? "#86efac" : "#93c5fd" }}>{item.status}</span></div>)}</div><div style={card}><small>Three-party digital stamp matrix</small><div style={stampGrid}>{([["contractor", "Contractor Signature Stamp", "#fbbf24"], ["consultant", "Consultant / Architect Verification Stamp", "#60a5fa"], ["client", "Client Final Approval Stamp", "#34d399"]] as const).map(([key, label, color]) => <button key={key} type="button" disabled={key !== "contractor" && !stamps["contractor"] || key === "client" && !stamps.consultant} onClick={() => approve(key)} style={{ ...stamp, color, borderColor: `${color}66`, opacity: stamps[key] ? 1 : .7 }}>{stamps[key] ? "SIGNED · " : "PENDING · "}{label}</button>)}</div></div><button type="button" onClick={exportPdf} style={secondary}>Export Official DPR PDF</button></>}</section>; }
const eyebrow = { color: "#7dd3fc", fontSize: 11, letterSpacing: ".16em", textTransform: "uppercase" as const }; const grid = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: 12 }; const card = { background: "#111827", borderRadius: 14, padding: 14, display: "grid", gap: 8 }; const stampGrid = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(190px,1fr))", gap: 10, marginTop: 12 }; const stamp = { background: "rgba(2,6,23,.55)", border: "1px solid", borderRadius: 10, padding: "12px 10px", textAlign: "left" as const, cursor: "pointer", fontWeight: 800, fontSize: 11 }; const button = { border: "1px solid rgba(34,211,238,.4)", background: "rgba(34,211,238,.12)", color: "#cffafe", borderRadius: 10, padding: "11px 14px", fontWeight: 800, cursor: "pointer" }; const secondary = { ...button, borderColor: "rgba(148,163,184,.3)", background: "rgba(148,163,184,.08)" };
