"use client";

import { useEffect, useRef, useState } from "react";
import type { PanoramaSnapshot } from "@/types/construction";

const snapshots: PanoramaSnapshot[] = [
  { id: "pano-12", projectId: "proj-1", capturedAt: "2026-06-12", weekLabel: "Week 12 · Bare concrete", location: "North Tower / Level 03", imageUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1800&q=80" },
  { id: "pano-15", projectId: "proj-1", capturedAt: "2026-07-03", weekLabel: "Week 15 · MEP rough-in", location: "North Tower / Level 03", imageUrl: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1800&q=80" },
  { id: "pano-18", projectId: "proj-1", capturedAt: "2026-07-24", weekLabel: "Week 18 · MEP piping", location: "North Tower / Level 03", imageUrl: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=1800&q=80" },
];

export function PanoramaViewer360() { const [index, setIndex] = useState(2); const [yaw, setYaw] = useState(0); const [fov, setFov] = useState(75); const [dragging, setDragging] = useState(false); const startX = useRef(0); const snapshot = snapshots[index]; useEffect(() => { const stop = () => setDragging(false); window.addEventListener("mouseup", stop); return () => window.removeEventListener("mouseup", stop); }, []); const startDrag = (event: React.MouseEvent<HTMLCanvasElement>) => { setDragging(true); startX.current = event.clientX; }; const move = (event: React.MouseEvent<HTMLCanvasElement>) => { if (!dragging) return; setYaw((current) => current + (event.clientX - startX.current) * .3); startX.current = event.clientX; }; return <section style={shell}><div style={floorplan}><div style={eyebrow}>2D floorplan sheet</div><h2 style={title}>360 site walk hotspots</h2><div style={plan}><div style={building}>Level 03 / North Tower</div>{[{ left: "25%", top: "32%", label: "Grid B2" }, { left: "67%", top: "28%", label: "MEP riser" }, { left: "50%", top: "70%", label: "Core" }].map((pin) => <button key={pin.label} type="button" onClick={() => setIndex(pin.label === "Grid B2" ? 0 : pin.label === "MEP riser" ? 2 : 1)} style={{ ...pinStyle, left: pin.left, top: pin.top }} aria-label={`Load ${pin.label} panorama`}>●</button>)}</div><div style={hint}>Click a hotspot to load the matching spatial capture.</div></div><div style={viewer}><div style={viewerHeader}><div><div style={eyebrow}>WebGL equirectangular panorama surface</div><h2 style={title}>{snapshot.weekLabel}</h2><div style={muted}>{snapshot.location} · {snapshot.capturedAt}</div></div><label style={control}>FOV <input type="range" min="45" max="110" value={fov} onChange={(event) => setFov(Number(event.target.value))} /></label></div><canvas width="900" height="500" onMouseDown={startDrag} onMouseMove={move} style={{ ...canvas, cursor: dragging ? "grabbing" : "grab", backgroundImage: `url(${snapshot.imageUrl})`, backgroundPosition: `${50 + yaw / 8}% center`, backgroundSize: `${Math.max(100, 110 - (fov - 45) * .65)}% auto` }} aria-label="Interactive 360 degree panorama viewer" /><div style={sliderRow}><span style={muted}>Time-travel progress</span><input type="range" min="0" max={snapshots.length - 1} value={index} onChange={(event) => setIndex(Number(event.target.value))} style={{ flex: 1 }} /><strong>{snapshot.capturedAt}</strong></div></div></section>; }

const shell: React.CSSProperties = { display: "grid", gridTemplateColumns: "minmax(260px, .75fr) minmax(0, 1.6fr)", gap: 18 }; const floorplan: React.CSSProperties = { background: "#0b1220", border: "1px solid #1e293b", borderRadius: 16, padding: 18 }; const viewer: React.CSSProperties = { background: "#0b1220", border: "1px solid #1e293b", borderRadius: 16, padding: 18 }; const eyebrow: React.CSSProperties = { color: "#67e8f9", fontSize: 10, letterSpacing: ".15em", textTransform: "uppercase", fontWeight: 800 }; const title: React.CSSProperties = { margin: "7px 0 0", fontSize: 20 }; const muted: React.CSSProperties = { color: "#94a3b8", fontSize: 12, marginTop: 5 }; const plan: React.CSSProperties = { position: "relative", height: 360, marginTop: 18, border: "1px solid #334155", background: "repeating-linear-gradient(0deg, transparent 0 35px, #334155 36px), repeating-linear-gradient(90deg, transparent 0 35px, #334155 36px)" }; const building: React.CSSProperties = { position: "absolute", left: "15%", top: "14%", width: "70%", height: "72%", display: "grid", placeItems: "center", border: "2px solid #e2e8f0", background: "#e2e8f00d", color: "#cbd5e1", fontSize: 12 }; const pinStyle: React.CSSProperties = { position: "absolute", transform: "translate(-50%, -50%)", border: 0, background: "#f59e0b", color: "#111827", borderRadius: 999, width: 26, height: 26, cursor: "pointer", boxShadow: "0 0 0 6px #f59e0b33" }; const hint: React.CSSProperties = { color: "#64748b", fontSize: 11, marginTop: 12 }; const viewerHeader: React.CSSProperties = { display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 12, flexWrap: "wrap", marginBottom: 16 }; const control: React.CSSProperties = { display: "flex", alignItems: "center", gap: 8, color: "#cbd5e1", fontSize: 11 }; const canvas: React.CSSProperties = { width: "100%", height: "auto", minHeight: 320, objectFit: "cover", border: "1px solid #334155", display: "block", backgroundColor: "#162a36", backgroundRepeat: "no-repeat" }; const sliderRow: React.CSSProperties = { display: "flex", alignItems: "center", gap: 12, marginTop: 14, fontSize: 11 };