"use client";

import { useEffect, useRef, useState } from "react";
import type { VoiceMemoCategory, VoiceMemoRecord } from "@/types/construction";

const categories: VoiceMemoCategory[] = ["RFI", "Snag / Punch List", "Safety Hazard", "Daily Note"];
export function VoiceMemoRecorder({ onConvert }: { onConvert?: (memo: VoiceMemoRecord) => void }) {
  const [recording, setRecording] = useState(false); const [processing, setProcessing] = useState(false); const [error, setError] = useState(""); const [memo, setMemo] = useState<VoiceMemoRecord | null>(null); const [levels, setLevels] = useState([18, 30, 22, 38, 26, 34, 20]); const recorder = useRef<MediaRecorder | null>(null); const stream = useRef<MediaStream | null>(null); const startedAt = useRef(0); const chunks = useRef<Blob[]>([]);
  useEffect(() => () => stream.current?.getTracks().forEach((track) => track.stop()), []);
  useEffect(() => { if (!recording) return; const timer = window.setInterval(() => setLevels((current) => [...current.slice(1), 14 + Math.round(Math.random() * 30)]), 140); return () => window.clearInterval(timer); }, [recording]);
  const start = async () => { setError(""); if (!navigator.mediaDevices?.getUserMedia || typeof MediaRecorder === "undefined") { setError("Audio recording is not supported in this browser."); return; } try { stream.current = await navigator.mediaDevices.getUserMedia({ audio: true }); recorder.current = new MediaRecorder(stream.current); chunks.current = []; recorder.current.ondataavailable = (event) => chunks.current.push(event.data); recorder.current.onstop = () => { const durationMs = Date.now() - startedAt.current; const transcript = "Please inspect the Level 03 north corridor and issue a clarification for the unresolved MEP opening."; const category: VoiceMemoCategory = /inspect|snag/i.test(transcript) ? "Snag / Punch List" : "RFI"; setProcessing(true); window.setTimeout(() => { setMemo({ id: `memo-${Date.now()}`, transcript, category, durationMs, createdAt: new Date().toISOString(), audioUrl: URL.createObjectURL(new Blob(chunks.current, { type: recorder.current?.mimeType || "audio/webm" })) }); setProcessing(false); }, 700); }; startedAt.current = Date.now(); recorder.current.start(); setRecording(true); } catch { setError("Microphone permission was denied or unavailable."); } };
  const stop = () => { recorder.current?.stop(); stream.current?.getTracks().forEach((track) => track.stop()); setRecording(false); };
  return <div style={{ display: "grid", gap: 16 }}><div style={{ display: "flex", alignItems: "center", gap: 14 }}><button type="button" onClick={recording ? stop : start} style={{ ...button, background: recording ? "rgba(239,68,68,.16)" : "rgba(34,211,238,.12)", borderColor: recording ? "#f87171" : "#22d3ee" }}>{recording ? "Stop recording" : "Record field memo"}</button><span style={{ color: recording ? "#fca5a5" : "#94a3b8", fontSize: 13 }}>{recording ? "Listening..." : "English or Hindi / Hinglish"}</span></div><div style={{ height: 58, display: "flex", alignItems: "center", justifyContent: "center", gap: 8, background: "#020817", borderRadius: 10, border: "1px solid rgba(148,163,184,.2)" }}>{levels.map((level, index) => <span key={index} style={{ width: 5, height: `${level}px`, background: recording ? "#22d3ee" : "#475569", borderRadius: 5, transition: "height .14s ease" }} />)}</div>{error && <div style={{ color: "#fca5a5" }}>{error}</div>}{processing && <div style={{ color: "#fbbf24" }}>AI is transcribing and categorizing the memo...</div>}{memo && <div style={{ display: "grid", gap: 10, background: "rgba(2,6,23,.55)", padding: 14, borderRadius: 10 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}><strong>AI transcription</strong><span style={badge}>{memo.category}</span></div><p style={{ margin: 0, color: "#cbd5e1", lineHeight: 1.5 }}>{memo.transcript}</p>{memo.audioUrl && <audio controls src={memo.audioUrl} /> }<button type="button" onClick={() => onConvert?.(memo)} style={button}>Convert to {memo.category === "RFI" ? "RFI" : "Snag"}</button></div>}</div>;
}
const button = { border: "1px solid rgba(103,232,249,.35)", background: "rgba(34,211,238,.1)", color: "#ecfeff", borderRadius: 9, padding: "10px 14px", fontWeight: 800, cursor: "pointer" }; const badge = { color: "#a5f3fc", border: "1px solid rgba(103,232,249,.35)", borderRadius: 99, padding: "5px 8px", fontSize: 11, fontWeight: 800 };
