"use client";

import { useState } from "react";
import type { LaborSkillTier, WorkforceMusterEntry } from "@/types/construction";

export function WorkforceProductivityDrawer({ entry, onClose, onUpdated }: { entry: WorkforceMusterEntry | null; onClose: () => void; onUpdated: (entry: WorkforceMusterEntry) => void }) {
  const [draft, setDraft] = useState(entry);
  if (!draft) return null;
  const manDays = Math.max(draft.actualHeadcount, 1);
  const productivity = draft.unitsInstalled / manDays;
  const payout = draft.actualHeadcount * draft.wageRatePerDay + draft.actualHeadcount * (draft.wageRatePerDay / 8) * draft.overtimeHours * 2;
  const minimumWageAlert = draft.wageRatePerDay < 700;
  const exportMuster = () => { const popup = window.open("", "_blank"); if (!popup) return; popup.document.write(`<html><body style="font-family:Arial;padding:40px"><h1>Contractor Labor Wage Muster Sheet</h1><p>Trade: ${draft.trade} / Skill tier: ${draft.skillTier}</p><p>Biometric headcount: ${draft.actualHeadcount} / In: ${draft.biometricInAt}</p><p>Regular wage: INR ${draft.wageRatePerDay} / OT: ${draft.overtimeHours} hours</p><p>Statutory payout: INR ${payout.toFixed(2)}</p><p>Productivity index: ${productivity.toFixed(2)} units/man-day</p><p>BOCW cess: ${draft.bocwCessVerified ? "Verified" : "Pending"} · PF/ESIC: ${draft.pfEsicVerified ? "Verified" : "Pending"}</p><p>Digital contractor signature: ____________________</p></body></html>`); popup.document.close(); popup.print(); };
  return <div style={overlay}><div style={modal}><div style={header}><div><div style={eyebrow}>Biometric muster / statutory payroll</div><h2 style={{ margin: "6px 0 0", fontSize: 23 }}>{draft.trade} · {draft.skillTier}</h2></div><button type="button" onClick={onClose} style={close} aria-label="Close workforce drawer">×</button></div><div style={metrics}><div><span>Productivity index</span><strong>{productivity.toFixed(2)} units/man-day</strong></div><div><span>Statutory payout</span><strong>₹{payout.toLocaleString("en-IN", { maximumFractionDigits: 0 })}</strong></div><div><span>Biometric turnstile</span><strong>{draft.biometricInAt} · Active</strong></div></div><div style={form}><label>Skill tier<select value={draft.skillTier} onChange={(event) => setDraft({ ...draft, skillTier: event.target.value as LaborSkillTier })} style={input}>{["Skilled", "Semi-skilled", "Unskilled"].map((tier) => <option key={tier}>{tier}</option>)}</select></label><label>Units installed<input type="number" value={draft.unitsInstalled} onChange={(event) => setDraft({ ...draft, unitsInstalled: Number(event.target.value) })} style={input} /></label><label>Wage rate (₹/day)<input type="number" value={draft.wageRatePerDay} onChange={(event) => setDraft({ ...draft, wageRatePerDay: Number(event.target.value) })} style={input} /></label><label>Overtime hours<input type="number" value={draft.overtimeHours} onChange={(event) => setDraft({ ...draft, overtimeHours: Number(event.target.value) })} style={input} /></label></div><div style={toggles}><label><input type="checkbox" checked={draft.bocwCessVerified} onChange={(event) => setDraft({ ...draft, bocwCessVerified: event.target.checked })} /> 1% BOCW cess compliance</label><label><input type="checkbox" checked={draft.pfEsicVerified} onChange={(event) => setDraft({ ...draft, pfEsicVerified: event.target.checked })} /> PF/ESIC muster verified</label><span style={{ color: minimumWageAlert ? "#f87171" : "#86efac" }}>{minimumWageAlert ? "Underpayment / minimum wage alert" : "Minimum wage check passed"}</span></div><div style={actions}><button type="button" onClick={exportMuster} style={secondary}>Export Contractor Labor Wage Muster Sheet</button><button type="button" onClick={() => { onUpdated(draft); onClose(); }} style={primary}>Save muster verification</button></div></div></div>;
}
const overlay = { position: "fixed" as const, inset: 0, zIndex: 100, display: "grid", placeItems: "center", padding: 20, background: "rgba(2,6,23,.82)" }; const modal = { width: "min(700px,100%)", background: "#0b1220", border: "1px solid #334155", borderRadius: 20, padding: 24, color: "#e2e8f0", display: "grid", gap: 18 }; const header = { display: "flex", justifyContent: "space-between", alignItems: "flex-start" }; const eyebrow = { color: "#7dd3fc", fontSize: 11, letterSpacing: ".14em", textTransform: "uppercase" as const }; const close = { width: 34, height: 34, borderRadius: 999, border: "1px solid #334155", background: "transparent", color: "#f8fafc", cursor: "pointer", fontSize: 20 }; const metrics = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(150px,1fr))", gap: 10 }; const form = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: 12 }; const label = { display: "grid", gap: 6, color: "#cbd5e1", fontSize: 12 }; const input = { width: "100%", boxSizing: "border-box" as const, border: "1px solid #334155", borderRadius: 8, background: "#111827", color: "#f8fafc", padding: 10 }; const toggles = { display: "grid", gap: 10, background: "#111827", borderRadius: 10, padding: 14, fontSize: 12 }; const actions = { display: "flex", justifyContent: "flex-end", gap: 10, flexWrap: "wrap" as const }; const primary = { border: 0, borderRadius: 9, background: "#22c55e", color: "#052e16", padding: "10px 14px", fontWeight: 800, cursor: "pointer" }; const secondary = { border: "1px solid #334155", borderRadius: 9, background: "transparent", color: "#cbd5e1", padding: "10px 14px", cursor: "pointer" };
