"use client";

import { useEffect, useMemo, useState } from "react";
import { BimModelViewer } from "@/components/viewer/BimModelViewer";
import type { BimClashRecord, ProjectScheduleTask } from "@/types/construction";

export function Bim4DTimelinePlayer({ tasks, clashes = [] }: { tasks: ProjectScheduleTask[]; clashes?: BimClashRecord[] }) {
  const bounds = useMemo(() => { const dates = tasks.flatMap((task) => [Date.parse(task.baselineStart), Date.parse(task.baselineFinish)]).filter(Number.isFinite); const start = dates.length ? Math.min(...dates) : Date.parse("2026-04-01"); const end = dates.length ? Math.max(...dates) : Date.parse("2026-11-01"); return { start, end: Math.max(start + 86400000, end) }; }, [tasks]);
  const [time, setTime] = useState(bounds.start); const [playing, setPlaying] = useState(false); const [speed, setSpeed] = useState(1);
  useEffect(() => { if (!playing) return; const timer = window.setInterval(() => setTime((value) => Math.min(bounds.end, value + 86400000 * speed)), 700); return () => window.clearInterval(timer); }, [bounds.end, playing, speed]);
  const step = (direction: number) => setTime((value) => Math.min(bounds.end, Math.max(bounds.start, value + direction * 86400000)));
  return <section style={panel}><div style={header}><div><div style={eyebrow}>BIM / schedule sequence</div><h2 style={{ margin: "6px 0 0", fontSize: 22 }}>4D construction time-lapse player</h2></div><strong style={{ color: "#7dd3fc" }}>{new Date(time).toISOString().slice(0, 10)}</strong></div><div style={controls}><button type="button" onClick={() => setPlaying((value) => !value)} style={button}>{playing ? "Pause" : "Play"}</button><button type="button" onClick={() => step(1)} style={button}>Step forward</button><input type="range" min={bounds.start} max={bounds.end} value={time} onChange={(event) => setTime(Number(event.target.value))} aria-label="4D timeline scrubber" style={{ flex: 1, minWidth: 180 }}/>{[1, 2, 5].map((value) => <button type="button" key={value} onClick={() => setSpeed(value)} style={{ ...button, background: speed === value ? "#0ea5e9" : "#111827" }}>{value}x</button>)}</div><div style={legend}><span style={{ color: "#94a3b8" }}>Ghost: planned future</span><span style={{ color: "#fbbf24" }}>Amber: in progress / pouring</span><span style={{ color: "#34d399" }}>Teal: completed</span><span style={{ color: "#f87171" }}>Red: delayed vs baseline</span></div><div style={split}><div><div style={eyebrow}>Planned baseline</div><BimModelViewer clashes={clashes} tasks={tasks} playbackTime={time} showPlaybackControls={false}/></div><div><div style={eyebrow}>Actual as-built</div><BimModelViewer clashes={clashes} tasks={tasks.map((task) => ({ ...task, status: task.actualFinish && Date.parse(task.actualFinish) <= time ? "Complete" : task.status }))} playbackTime={time} showPlaybackControls={false}/></div></div></section>;
}
const panel = { background: "#0b1220", border: "1px solid #1e293b", borderRadius: 18, padding: 20 }; const header = { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "center", flexWrap: "wrap" as const }; const eyebrow = { color: "#7dd3fc", fontSize: 11, letterSpacing: ".14em", textTransform: "uppercase" as const }; const controls = { display: "flex", alignItems: "center", gap: 8, marginTop: 18, flexWrap: "wrap" as const }; const button = { border: "1px solid #334155", borderRadius: 8, background: "#111827", color: "#e2e8f0", padding: "8px 11px", cursor: "pointer" }; const legend = { display: "flex", gap: 14, flexWrap: "wrap" as const, fontSize: 11, marginTop: 12 }; const split = { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14, marginTop: 18 };
