"use client";

import { useEffect, useRef, useState } from "react";
import { supabase } from "@/app/lib/supabase";

type SpatialPin = { id: string; x: number; y: number; z: number; author: string; note: string; createdAt: string };

const initialPins: SpatialPin[] = [{ id: "sp-01", x: -2, y: 1.8, z: -4, author: "A. Mehta", note: "Check MEP clearance above beam soffit.", createdAt: "2026-08-25T08:40:00Z" }];

export function WebXRSpatialViewport() {
  const canvasRef = useRef<HTMLCanvasElement | null>(null); const [pins, setPins] = useState(initialPins); const [selected, setSelected] = useState<SpatialPin | null>(initialPins[0]); const [yaw, setYaw] = useState(0); const [zoom, setZoom] = useState(1); const [sync, setSync] = useState(false); const [roomCount, setRoomCount] = useState(1);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (["a", "d"].includes(event.key.toLowerCase())) setYaw((current) => current + (event.key.toLowerCase() === "a" ? -4 : 4)); if (["w", "s"].includes(event.key.toLowerCase())) setZoom((current) => Math.max(.7, Math.min(1.4, current + (event.key.toLowerCase() === "w" ? .05 : -.05)))); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, []);
  useEffect(() => { if (!sync || !supabase) return; const channel = supabase.channel("vr-telepresence-proj-1", { config: { presence: { key: "site-engineer" } } }); channel.on("presence", { event: "sync" }, () => setRoomCount(Object.keys(channel.presenceState()).length)); channel.subscribe(async (status) => { if (status === "SUBSCRIBED") await channel.track({ role: "Site Engineer", joinedAt: new Date().toISOString() }); }); return () => { void supabase.removeChannel(channel); }; }, [sync]);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const context = canvas.getContext("2d"); if (!context) return; const width = canvas.width; const height = canvas.height; context.fillStyle = "#071522"; context.fillRect(0, 0, width, height); context.strokeStyle = "#1e5264"; context.lineWidth = 1; for (let line = 0; line < 10; line += 1) { const x = width / 2 + (line - 5) * 95 + yaw * 3; context.beginPath(); context.moveTo(width / 2, height * .48); context.lineTo(x, height); context.stroke(); } context.strokeStyle = "#155e75"; context.strokeRect(90, 90, width - 180, height - 180); pins.forEach((pin) => { const screenX = width / 2 + (pin.x * 55 + yaw * 3) * zoom; const screenY = height * .5 - pin.y * 55 * zoom; context.fillStyle = selected?.id === pin.id ? "#fbbf24" : "#34d399"; context.beginPath(); context.arc(screenX, screenY, selected?.id === pin.id ? 9 : 7, 0, Math.PI * 2); context.fill(); context.fillStyle = "#e2e8f0"; context.font = "13px sans-serif"; context.fillText(pin.author, screenX + 12, screenY - 8); }); }, [pins, selected, yaw, zoom]);
  const addPin = (event: React.MouseEvent<HTMLCanvasElement>) => { const rect = event.currentTarget.getBoundingClientRect(); const x = (event.clientX - rect.left - rect.width / 2) / rect.width * 10; const y = (rect.height / 2 - (event.clientY - rect.top)) / rect.height * 10; const pin = { id: `sp-${Date.now()}`, x, y, z: -4, author: "Current user", note: "New spatial design markup", createdAt: new Date().toISOString() }; setPins((current) => [...current, pin]); setSelected(pin); };
  return <section style={shell}><div style={header}><div><div style={eyebrow}>WebXR / telepresence room</div><h2 style={title}>1:1 scale BIM spatial viewport</h2><div style={muted}>Desktop walkthrough active · WASD navigation · click model surface to pin</div></div><label style={toggle}><input type="checkbox" checked={sync} onChange={(event) => setSync(event.target.checked)} /> Sync realtime multi-user room <span>{sync ? `${roomCount} attendee${roomCount === 1 ? "" : "s"}` : "offline"}</span></label></div><div style={viewport}><canvas ref={canvasRef} width={900} height={500} onClick={addPin} style={canvas} aria-label="WebXR spatial BIM viewport" />{selected && <aside style={tooltip}><div style={eyebrow}>Spatial pin · {selected.x.toFixed(1)}, {selected.y.toFixed(1)}, {selected.z.toFixed(1)}</div><strong style={{ display: "block", marginTop: 8 }}>{selected.author}</strong><div style={muted}>{selected.note}</div><div style={timestamp}>{new Date(selected.createdAt).toLocaleString()}</div></aside>}</div><div style={pinList}>{pins.map((pin) => <button key={pin.id} type="button" onClick={() => setSelected(pin)} style={pinButton}>{pin.author} · {pin.note}</button>)}<span style={muted}>{pins.length} spatial annotation{pins.length === 1 ? "" : "s"}</span></div></section>;
}

const shell: React.CSSProperties = { background: "#0b1220", border: "1px solid #1e293b", borderRadius: 16, padding: 20 }; const header: React.CSSProperties = { display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 14, flexWrap: "wrap" }; const eyebrow: React.CSSProperties = { color: "#67e8f9", fontSize: 10, letterSpacing: ".15em", textTransform: "uppercase", fontWeight: 800 }; const title: React.CSSProperties = { margin: "7px 0 0", fontSize: 22 }; const muted: React.CSSProperties = { color: "#94a3b8", fontSize: 12, marginTop: 5 }; const toggle: React.CSSProperties = { display: "flex", gap: 8, alignItems: "center", color: "#cbd5e1", fontSize: 12 }; const viewport: React.CSSProperties = { position: "relative", marginTop: 17, overflow: "hidden", border: "1px solid #155e75", borderRadius: 12 }; const canvas: React.CSSProperties = { display: "block", width: "100%", height: "auto", minHeight: 350, cursor: "crosshair" }; const tooltip: React.CSSProperties = { position: "absolute", right: 14, top: 14, width: 230, padding: 14, background: "rgba(2,6,23,.94)", border: "1px solid #fbbf24", borderRadius: 10 }; const timestamp: React.CSSProperties = { color: "#64748b", fontSize: 10, marginTop: 9 }; const pinList: React.CSSProperties = { display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center", marginTop: 13 }; const pinButton: React.CSSProperties = { border: "1px solid #334155", borderRadius: 8, background: "#111827", color: "#cbd5e1", padding: "7px 9px", cursor: "pointer", fontSize: 11 };