"use client";

import { useState } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { WasteManifest } from "@/types/construction";

export function WasteDiversionTracker() {
  const [manifests, setManifests] = useState<WasteManifest[]>([{ id: "wm-01", date: "2026-08-25", stream: "Concrete rubble", quantityTonnes: 18.4, destination: "On-site sub-base recycling", haulingContractor: "GreenRoute Haulage", weighbridgeSlip: "WB-8821" }, { id: "wm-02", date: "2026-08-25", stream: "Ferrous scrap", quantityTonnes: 7.2, destination: "External scrap mill", haulingContractor: "Metro Recyclers", weighbridgeSlip: "WB-8822" }, { id: "wm-03", date: "2026-08-25", stream: "Mixed inert", quantityTonnes: 3.8, destination: "Landfill", haulingContractor: "Civic Haulage", weighbridgeSlip: "WB-8823" }]);
  const [form, setForm] = useState({ stream: "Concrete rubble" as WasteManifest["stream"], quantityTonnes: 0, destination: "On-site sub-base recycling" as WasteManifest["destination"], haulingContractor: "", weighbridgeSlip: "" });
  const total = manifests.reduce((sum, item) => sum + item.quantityTonnes, 0); const diverted = manifests.filter((item) => item.destination !== "Landfill").reduce((sum, item) => sum + item.quantityTonnes, 0); const rate = total ? diverted / total * 100 : 0;
  const addManifest = () => { if (!form.quantityTonnes || !form.haulingContractor || !form.weighbridgeSlip) return; setManifests((current) => [{ ...form, id: `wm-${Date.now()}`, date: new Date().toISOString().slice(0, 10) }, ...current]); setForm({ ...form, quantityTonnes: 0 }); };
  const status = rate >= 85 ? ["Target Exceeded (≥ 85%)", "#34d399"] : rate >= 75 ? ["Compliant (≥ 75%)", "#60a5fa"] : ["Below Green Target", "#fbbf24"];
  const chart = ["On-site sub-base recycling", "External scrap mill", "Licensed recovery", "Landfill"].map((destination) => ({ destination: destination.replace("On-site sub-base recycling", "On-site recycling").replace("External scrap mill", "Scrap mill").replace("Licensed recovery", "Recovery"), tonnes: manifests.filter((item) => item.destination === destination).reduce((sum, item) => sum + item.quantityTonnes, 0) }));
  return <section style={panel}><div style={header}><div><div style={eyebrow}>IGBC / LEED circular materials</div><h2 style={{ margin: "6px 0 0", fontSize: 22 }}>C&D waste diversion manager</h2></div><span style={{ ...badge, color: status[1] }}>{status[0]}</span></div><div style={topline}><div><span>Landfill diversion</span><strong style={{ color: status[1] }}>{rate.toFixed(1)}%</strong><small>Target ≥ 75% for Gold / Platinum pathways</small></div><div style={dial}><div style={{ ...dialFill, background: `conic-gradient(${status[1]} ${rate}%, #1f2937 0)` }}><div style={dialCore}>{rate.toFixed(0)}%</div></div></div></div><div style={{ height: 230 }}><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid stroke="rgba(148,163,184,.12)" vertical={false}/><XAxis dataKey="destination" tick={{ fill: "#cbd5e1", fontSize: 10 }}/><YAxis tick={{ fill: "#cbd5e1" }}/><Tooltip contentStyle={{ background: "#0f172a", border: "1px solid #334155" }}/><Bar dataKey="tonnes" name="Tonnes" fill="#38bdf8" radius={[5, 5, 0, 0]}/></BarChart></ResponsiveContainer></div><div style={formGrid}><select value={form.stream} onChange={(event) => setForm({ ...form, stream: event.target.value as WasteManifest["stream"] })} style={input}>{["Concrete rubble", "Ferrous scrap", "Timber", "Packaging", "Mixed inert"].map((item) => <option key={item}>{item}</option>)}</select><input type="number" placeholder="Tonnes" value={form.quantityTonnes || ""} onChange={(event) => setForm({ ...form, quantityTonnes: Number(event.target.value) })} style={input}/><select value={form.destination} onChange={(event) => setForm({ ...form, destination: event.target.value as WasteManifest["destination"] })} style={input}>{["On-site sub-base recycling", "External scrap mill", "Licensed recovery", "Landfill"].map((item) => <option key={item}>{item}</option>)}</select><input placeholder="Hauling contractor" value={form.haulingContractor} onChange={(event) => setForm({ ...form, haulingContractor: event.target.value })} style={input}/><input placeholder="Weighbridge slip" value={form.weighbridgeSlip} onChange={(event) => setForm({ ...form, weighbridgeSlip: event.target.value })} style={input}/><button type="button" onClick={addManifest} style={button}>Log waste manifest</button></div></section>;
}
const panel = { background: "#0b1220", border: "1px solid #1e293b", borderRadius: 18, padding: 20 }; const header = { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap" as const }; const eyebrow = { color: "#7dd3fc", fontSize: 11, letterSpacing: ".15em", textTransform: "uppercase" as const }; const badge = { borderRadius: 999, background: "rgba(255,255,255,.06)", padding: "7px 10px", fontSize: 11, fontWeight: 700 }; const topline = { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 20, margin: "20px 0" }; const dial = { width: 100, height: 100, display: "grid", placeItems: "center" }; const dialFill = { width: "100%", height: "100%", borderRadius: "50%", display: "grid", placeItems: "center" }; const dialCore = { width: 76, height: 76, borderRadius: "50%", display: "grid", placeItems: "center", background: "#0b1220", fontWeight: 800, fontSize: 20 }; const formGrid = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(150px,1fr))", gap: 10, marginTop: 16 }; const input = { width: "100%", boxSizing: "border-box" as const, border: "1px solid #334155", borderRadius: 8, background: "#111827", color: "#f8fafc", padding: "10px" }; const button = { border: 0, borderRadius: 8, background: "#38bdf8", color: "#082f49", padding: "10px", fontWeight: 800, cursor: "pointer" }; 