"use client";

import { useState } from "react";
import type { ITPStageGate, ITPStageGateType } from "@/types/construction";

export function ITPStageGateMatrix({ initialGates }: { initialGates: ITPStageGate[] }) {
  const [gates, setGates] = useState(initialGates);
  const [evidence, setEvidence] = useState<Record<string, string>>({});
  const blocked = gates.some((gate) => gate.critical && gate.gateType === "Hold Point (Mandatory Stop)" && gate.status !== "Stage Cleared");
  const upload = (id: string, event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) setEvidence((current) => ({ ...current, [id]: file.name })); };
  const clear = (gate: ITPStageGate) => { if (!evidence[gate.id]) return; setGates((current) => current.map((item) => item.id === gate.id ? { ...item, status: "Stage Cleared", evidenceFileName: evidence[gate.id], signedBy: "Consultant Engineer", signedAt: new Date().toISOString() } : item)); };
  return <div style={{ display: "grid", gap: 16 }}>{blocked && <div style={warning}><strong>MANDATORY HOLD POINT ACTIVE</strong><span>Related WIRs and concrete pours remain blocked until the critical ITP stage is cleared.</span></div>}<div style={timeline}>{gates.map((gate) => <article key={gate.id} style={card}><div style={cardHeader}><div><div style={eyebrow}>{gate.gateType}</div><h3 style={{ margin: "7px 0 0", fontSize: 19 }}>{gate.stage}</h3></div><span style={statusStyle(gate.status)}>{gate.status}</span></div><div style={detail}>WIR: {gate.relatedWirNumbers.join(", ")} · Pour schedule: {gate.relatedPourSchedule}</div><div style={actions}><label style={uploadButton}>Upload calibration / test report<input type="file" onChange={(event) => upload(gate.id, event)} style={{ display: "none" }} /></label>{evidence[gate.id] && <span style={fileName}>{evidence[gate.id]}</span>}<button type="button" disabled={!evidence[gate.id] || gate.status === "Stage Cleared"} onClick={() => clear(gate)} style={{ ...clearButton, opacity: !evidence[gate.id] || gate.status === "Stage Cleared" ? .45 : 1 }}>Consultant sign off</button></div></article>)}</div></div>;
}

const statusStyle = (status: ITPStageGate["status"]): React.CSSProperties => ({ borderRadius: 999, padding: "6px 9px", fontSize: 10, fontWeight: 900, color: status === "Stage Cleared" ? "#86efac" : status === "Rejected" ? "#fca5a5" : "#fcd34d", background: status === "Stage Cleared" ? "#052e1633" : status === "Rejected" ? "#450a0a33" : "#451a0333" }); const warning: React.CSSProperties = { display: "grid", gap: 5, border: "1px solid #991b1b", borderRadius: 10, background: "#450a0a66", color: "#fecaca", padding: 15, fontSize: 12 }; const timeline: React.CSSProperties = { display: "grid", gap: 12 }; const card: React.CSSProperties = { background: "#0b1220", border: "1px solid #1e293b", borderRadius: 14, padding: 17 }; const cardHeader: React.CSSProperties = { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12 }; const eyebrow: React.CSSProperties = { color: "#67e8f9", fontSize: 10, letterSpacing: ".14em", textTransform: "uppercase", fontWeight: 800 }; const detail: React.CSSProperties = { marginTop: 13, color: "#94a3b8", fontSize: 12 }; const actions: React.CSSProperties = { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", marginTop: 15 }; const uploadButton: React.CSSProperties = { border: "1px solid #334155", borderRadius: 8, color: "#cbd5e1", padding: "8px 10px", fontSize: 11, fontWeight: 800, cursor: "pointer" }; const fileName: React.CSSProperties = { color: "#a5f3fc", fontSize: 11 }; const clearButton: React.CSSProperties = { border: 0, borderRadius: 8, background: "#34d399", color: "#052e16", padding: "9px 11px", fontWeight: 900, cursor: "pointer" };