"use client";

import { useState } from "react";
import type { NcrRecord, NcrSeverity } from "@/types/construction";

export function NCRDrawer({ ncr, onClose, onSave }: { ncr: NcrRecord; onClose: () => void; onSave: (ncr: NcrRecord) => void }) {
  const [record, setRecord] = useState(ncr);
  const [photoUrl, setPhotoUrl] = useState(ncr.photoUrl);
  const update = <K extends keyof NcrRecord>(key: K, value: NcrRecord[K]) => setRecord((current) => ({ ...current, [key]: value }));
  const stampClosure = async () => { const value = `${record.id}|${record.rootCause}|${record.rectificationPlan}|${new Date().toISOString()}`; const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); const hash = Array.from(new Uint8Array(bytes)).map((byte) => byte.toString(16).padStart(2, "0")).join(""); onSave({ ...record, status: "Closed", closureStamp: `CONSULTANT-CAPA-${hash.slice(0, 20)}` }); };
  return <div style={overlayStyle} role="dialog" aria-modal="true" aria-label="NCR and CAPA drawer"><aside style={drawerStyle}><header style={headerStyle}><div><div style={eyebrowStyle}>Quality governance · {record.ncrNumber}</div><h2 style={{ margin: "7px 0 0", fontSize: 24 }}>{record.title}</h2><div style={mutedStyle}>{record.locationZone} · {record.status}</div></div><button type="button" onClick={onClose} style={closeStyle}>×</button></header><section style={{ marginTop: 18 }}><label style={labelStyle}>Severity<select value={record.severity} onChange={(event) => update("severity", event.target.value as NcrSeverity)} style={inputStyle}><option>Critical / Stop Work</option><option>Major</option><option>Minor</option></select></label><label style={{ ...labelStyle, marginTop: 12 }}>Non-conformance summary<textarea value={record.summary} onChange={(event) => update("summary", event.target.value)} style={{ ...inputStyle, minHeight: 80 }} /></label><label style={{ ...labelStyle, marginTop: 12 }}>Cited IS / NBC specification<input value={record.specification} onChange={(event) => update("specification", event.target.value)} style={inputStyle} /></label></section><div style={{ marginTop: 18 }}><div style={eyebrowStyle}>Photo evidence</div>{photoUrl ? <img src={photoUrl} alt="NCR evidence" style={{ width: "100%", maxHeight: 170, objectFit: "cover", borderRadius: 9, marginTop: 8 }} /> : <input type="file" accept="image/*" onChange={(event) => { const file = event.target.files?.[0]; if (file) { const url = URL.createObjectURL(file); setPhotoUrl(url); update("photoUrl", url); } }} style={{ ...inputStyle, padding: 8, marginTop: 8 }} />}</div><section style={{ marginTop: 18, borderTop: "1px solid #263449", paddingTop: 16 }}><div style={eyebrowStyle}>Contractor CAPA response</div><label style={{ ...labelStyle, marginTop: 12 }}>Root-cause explanation<textarea value={record.rootCause ?? ""} onChange={(event) => update("rootCause", event.target.value)} placeholder="Describe the systemic cause" style={{ ...inputStyle, minHeight: 76 }} /></label><label style={{ ...labelStyle, marginTop: 12 }}>Rectification and preventive plan<textarea value={record.rectificationPlan ?? ""} onChange={(event) => update("rectificationPlan", event.target.value)} placeholder="Describe corrective and preventive action" style={{ ...inputStyle, minHeight: 76 }} /></label></section><div style={{ display: "flex", gap: 9, marginTop: 20, flexWrap: "wrap" }}><button type="button" onClick={() => onSave({ ...record, photoUrl })} style={secondaryButton}>Save CAPA response</button><button type="button" disabled={!record.rootCause || !record.rectificationPlan} onClick={() => void stampClosure()} style={{ ...primaryButton, opacity: record.rootCause && record.rectificationPlan ? 1 : .5 }}>Apply consultant closure stamp</button></div></aside></div>;
}
const overlayStyle: React.CSSProperties = { position: "fixed", inset: 0, zIndex: 60, display: "flex", justifyContent: "flex-end", background: "rgba(2,6,23,.82)" };
const drawerStyle: React.CSSProperties = { width: "min(650px, 100%)", height: "100%", overflowY: "auto", background: "#07111f", borderLeft: "1px solid #334155", padding: 24, color: "#f8fafc" };
const headerStyle: React.CSSProperties = { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12 };
const eyebrowStyle: React.CSSProperties = { color: "#67e8f9", fontSize: 11, letterSpacing: ".16em", textTransform: "uppercase", fontWeight: 800 };
const mutedStyle: React.CSSProperties = { color: "#94a3b8", fontSize: 12, marginTop: 5 };
const labelStyle: React.CSSProperties = { display: "grid", gap: 6, color: "#94a3b8", fontSize: 11, letterSpacing: ".08em", textTransform: "uppercase" };
const inputStyle: React.CSSProperties = { display: "block", width: "100%", boxSizing: "border-box", background: "#0f172a", color: "#f8fafc", border: "1px solid #334155", borderRadius: 8, padding: 10, resize: "vertical" };
const closeStyle: React.CSSProperties = { background: "transparent", border: "1px solid #334155", color: "#cbd5e1", borderRadius: 8, fontSize: 22, width: 34, height: 34, cursor: "pointer" };
const primaryButton: React.CSSProperties = { background: "#34d399", color: "#052e16", border: 0, borderRadius: 8, padding: "10px 12px", fontWeight: 900, cursor: "pointer" };
const secondaryButton: React.CSSProperties = { background: "#0ea5e9", color: "white", border: 0, borderRadius: 8, padding: "10px 12px", fontWeight: 800, cursor: "pointer" };
