"use client";

import { useMemo, useState } from "react";
import type { TenderBidRecord } from "@/types/construction";

export function qcbsScore(bid: TenderBidRecord) { return bid.technicalScore * .4 + (bid.baseBid / Math.max(bid.negotiatedBid, 1)) * 60; }

export function TenderComparativeTable({ initialBids }: { initialBids: TenderBidRecord[] }) {
  const [bids, setBids] = useState(initialBids);
  const responsive = useMemo(() => bids.filter((bid) => bid.status === "Responsive").sort((a, b) => qcbsScore(b) - qcbsScore(a)), [bids]);
  const generateLoi = (bid: TenderBidRecord) => { const body = `LETTER OF INTENT\n\nTender Package: ${bid.tenderPackage}\nContractor: ${bid.contractor}\nNegotiated Bid: INR ${bid.negotiatedBid.toLocaleString("en-IN")}\nQCBS Composite Score: ${qcbsScore(bid).toFixed(2)}\n\nYou are requested to proceed with contract finalization subject to the executed agreement.`; const printWindow = window.open("", "_blank"); if (!printWindow) return; printWindow.document.write(`<html><body style="font-family:Arial;padding:48px;white-space:pre-wrap">${body}</body></html>`); printWindow.document.close(); printWindow.focus(); printWindow.print(); };
  return <div style={{ display: "grid", gap: 14 }}><div style={header}><div><div style={eyebrow}>CST / QCBS evaluation</div><h2 style={title}>Tender comparative statement</h2></div><span style={muted}>{responsive.length} responsive bids ranked</span></div><div style={tableWrap}><table style={table}><thead><tr>{["Contractor / package", "Base bid", "Negotiated bid", "Technical / 40", "QCBS score", "Ranking", "LOI"].map((heading) => <th key={heading} style={th}>{heading}</th>)}</tr></thead><tbody>{bids.map((bid) => { const rank = bid.status === "Responsive" ? responsive.findIndex((item) => item.id === bid.id) + 1 : 0; const label = bid.status === "Disqualified / Non-Responsive" ? bid.status : rank === 1 ? "L1 (Lowest Bidder)" : `L${rank}`; return <tr key={bid.id}><td style={td}><strong>{bid.contractor}</strong><div style={muted}>{bid.tenderPackage}</div></td><td style={td}>₹{bid.baseBid.toLocaleString("en-IN")}</td><td style={td}><input type="number" value={bid.negotiatedBid} onChange={(event) => setBids((current) => current.map((item) => item.id === bid.id ? { ...item, negotiatedBid: Number(event.target.value) } : item))} style={numberInput} /></td><td style={td}><input type="number" min="0" max="100" value={bid.technicalScore} onChange={(event) => setBids((current) => current.map((item) => item.id === bid.id ? { ...item, technicalScore: Number(event.target.value) } : item))} style={numberInput} /></td><td style={td}>{bid.status === "Responsive" ? qcbsScore(bid).toFixed(2) : "-"}</td><td style={{ ...td, color: bid.status === "Disqualified / Non-Responsive" ? "#f87171" : rank === 1 ? "#86efac" : "#94a3b8", fontWeight: 800 }}>{label}</td><td style={td}>{rank === 1 && <button type="button" onClick={() => generateLoi(bid)} style={button}>Generate LOI</button>}</td></tr>; })}</tbody></table></div><div style={note}>QCBS = (Technical Score × 0.40) + ((Base Bid ÷ Negotiated Bid) × 60.0). Rankings recalculate as bids change.</div></div>;
}

const header: React.CSSProperties = { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "flex-end", flexWrap: "wrap" }; const eyebrow: React.CSSProperties = { color: "#67e8f9", fontSize: 10, letterSpacing: ".15em", textTransform: "uppercase", fontWeight: 800 }; const title: React.CSSProperties = { margin: "7px 0 0", fontSize: 22 }; const muted: React.CSSProperties = { color: "#94a3b8", fontSize: 12, marginTop: 5 }; const tableWrap: React.CSSProperties = { overflowX: "auto" }; const table: React.CSSProperties = { width: "100%", minWidth: 900, borderCollapse: "collapse" }; const th: React.CSSProperties = { padding: 12, textAlign: "left", color: "#64748b", fontSize: 10, textTransform: "uppercase", borderBottom: "1px solid #263449" }; const td: React.CSSProperties = { padding: 12, borderBottom: "1px solid #1f2937", fontSize: 12, verticalAlign: "top" }; const numberInput: React.CSSProperties = { width: 105, background: "#111827", color: "#f8fafc", border: "1px solid #334155", borderRadius: 6, padding: 7 }; const button: React.CSSProperties = { border: 0, borderRadius: 7, background: "#34d399", color: "#052e16", padding: "8px 10px", fontWeight: 900, cursor: "pointer" }; const note: React.CSSProperties = { color: "#64748b", fontSize: 11 };