"use client";

import { useState } from "react";
import type { VariationOrderRecord } from "@/types/construction";

export function VariationOrderModal({ order, onClose, onSave }: { order: VariationOrderRecord; onClose: () => void; onSave: (order: VariationOrderRecord) => void }) {
  const [record, setRecord] = useState(order);
  const direct = record.materialCost + record.laborCost + record.plantMachineryCost;
  const subtotal = direct * (1 + record.contractorProfitOverheadPercent / 100);
  const total = subtotal * (1 + record.gstPercent / 100);
  const update = <K extends keyof VariationOrderRecord>(key: K, value: VariationOrderRecord[K]) => setRecord((current) => ({ ...current, [key]: value }));
  const moveToAnalysis = () => onSave({ ...record, status: "Under Rate Analysis" });
  const certify = () => onSave({ ...record, status: "Under Rate Analysis", quantitySurveyorCertified: true });
  const sanction = () => onSave({ ...record, status: "Client Approved", clientSanctioned: true });
  return <div style={overlay} role="dialog" aria-modal="true" aria-label="Variation order modal"><div style={modal}><header style={header}><div><div style={eyebrow}>VO / CPWD rate analysis · {record.voNumber}</div><h2 style={{ margin: "7px 0 0", fontSize: 23 }}>Variation order review</h2></div><button type="button" onClick={onClose} style={close}>×</button></header><div style={formGrid}><label style={label}>Originator<select value={record.originatorCategory} onChange={(event) => update("originatorCategory", event.target.value as VariationOrderRecord["originatorCategory"])} style={input}>{["Client", "Architect / Consultant", "Contractor", "Site Condition"].map((value) => <option key={value}>{value}</option>)}</select></label><label style={label}>Schedule impact (days)<input type="number" value={record.scheduleImpactDays} onChange={(event) => update("scheduleImpactDays", Number(event.target.value))} style={input} /></label></div><label style={{ ...label, marginTop: 12 }}>Scope description<textarea value={record.scopeDescription} onChange={(event) => update("scopeDescription", event.target.value)} style={{ ...input, minHeight: 70 }} /></label><div style={costGrid}>{(["materialCost", "laborCost", "plantMachineryCost", "contractorProfitOverheadPercent", "gstPercent"] as const).map((key) => <label key={key} style={label}>{key.replace(/([A-Z])/g, " $1")}<input type="number" min="0" step="0.01" value={record[key]} onChange={(event) => update(key, Number(event.target.value))} style={input} /></label>)}</div><section style={analysis}><div><span>Direct cost</span><strong>₹{direct.toFixed(2)}</strong></div><div><span>Subtotal</span><strong>₹{subtotal.toFixed(2)}</strong></div><div><span>Total analyzed rate</span><strong style={{ color: "#86efac" }}>₹{total.toFixed(2)}</strong></div></section><div style={workflow}><Step label="Architect recommendation" complete={Boolean(record.architectRecommendation)} onClick={() => update("architectRecommendation", "Recommended for rate analysis")} /><Step label="QS certification" complete={Boolean(record.quantitySurveyorCertified)} onClick={certify} disabled={record.status === "Submitted"} /><Step label="Client final sanction" complete={Boolean(record.clientSanctioned)} onClick={sanction} disabled={!record.quantitySurveyorCertified} /></div><div style={actions}><button type="button" onClick={onClose} style={secondary}>Close</button><button type="button" onClick={moveToAnalysis} style={primary}>Submit for rate analysis</button></div></div></div>;
}

function Step({ label, complete, onClick, disabled }: { label: string; complete: boolean; onClick: () => void; disabled?: boolean }) { return <button type="button" onClick={onClick} disabled={disabled || complete} style={{ ...step, opacity: disabled ? .45 : 1, color: complete ? "#86efac" : "#cbd5e1" }}>{complete ? "✓" : "○"} {label}</button>; }
const overlay: React.CSSProperties = { position: "fixed", inset: 0, zIndex: 70, display: "grid", placeItems: "center", padding: 20, background: "rgba(2,6,23,.82)" }; const modal: React.CSSProperties = { width: "min(760px, 100%)", maxHeight: "90vh", overflow: "auto", background: "#0b1220", border: "1px solid #334155", borderRadius: 16, padding: 22, color: "#e2e8f0" }; const header: React.CSSProperties = { display: "flex", justifyContent: "space-between", alignItems: "flex-start" }; const close: React.CSSProperties = { width: 34, height: 34, borderRadius: 8, border: "1px solid #334155", background: "transparent", color: "#f8fafc", fontSize: 20, cursor: "pointer" }; const eyebrow: React.CSSProperties = { color: "#67e8f9", fontSize: 10, letterSpacing: ".15em", textTransform: "uppercase", fontWeight: 800 }; const label: React.CSSProperties = { display: "grid", gap: 6, color: "#cbd5e1", fontSize: 11, textTransform: "uppercase", letterSpacing: ".07em" }; const input: React.CSSProperties = { width: "100%", boxSizing: "border-box", background: "#111827", color: "#f8fafc", border: "1px solid #334155", borderRadius: 8, padding: 9 }; const formGrid: React.CSSProperties = { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginTop: 20 }; const costGrid: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 10, marginTop: 16 }; const analysis: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 10, marginTop: 18, padding: 14, background: "#0f172a", border: "1px solid #263449", borderRadius: 10 }; const workflow: React.CSSProperties = { display: "grid", gap: 8, marginTop: 18 }; const step: React.CSSProperties = { textAlign: "left", border: "1px solid #263449", borderRadius: 8, background: "#111827", padding: 10, cursor: "pointer" }; const actions: React.CSSProperties = { display: "flex", justifyContent: "flex-end", gap: 10, marginTop: 20 }; const primary: React.CSSProperties = { border: 0, borderRadius: 8, background: "#34d399", color: "#052e16", padding: "10px 12px", fontWeight: 900, cursor: "pointer" }; const secondary: React.CSSProperties = { border: "1px solid #334155", borderRadius: 8, background: "transparent", color: "#cbd5e1", padding: "10px 12px", cursor: "pointer" };