"use client";

import { useState } from "react";
import { WorkOrderDetailModal } from "@/components/finance/WorkOrderDetailModal";
import type { SubcontractorWorkOrder } from "@/types/construction";

const initialOrders: SubcontractorWorkOrder[] = [{ id: "wo-01", projectId: "proj-1", workOrderNumber: "WO-MEP-042", tradePackage: "MEP rough-in", subcontractor: "VoltEdge MEP", contractValue: 18500000, cumulativeClaimed: 9250000, retainageRate: 5, milestone: "Level 03 first fix", masterIpcFunded: true, status: "Ready for Authorization", lineItems: [{ description: "HVAC ductwork installation", amount: 5400000 }, { description: "Electrical containment", amount: 3850000 }] }, { id: "wo-02", projectId: "proj-1", workOrderNumber: "WO-STR-031", tradePackage: "Structural steel", subcontractor: "SteelSpan India", contractValue: 28000000, cumulativeClaimed: 11200000, retainageRate: 5, milestone: "Roof truss package", masterIpcFunded: false, status: "Hold - IPC Unfunded", lineItems: [{ description: "Roof truss fabrication", amount: 11200000 }] }];

export default function SubcontractorsPage() { const [orders, setOrders] = useState(initialOrders); const [selected, setSelected] = useState<SubcontractorWorkOrder | null>(null); return <main style={page}><div style={container}><header style={header}><div><div style={eyebrow}>Finance / supply chain liabilities</div><h1 style={title}>Subcontractor work order reconciler</h1><p style={muted}>Track back-to-back claims, retainage, and pay-when-paid IPC funding gates.</p></div></header><section style={grid}>{orders.map((order) => { const progress = Math.min(100, order.cumulativeClaimed / order.contractValue * 100); const net = order.cumulativeClaimed * (1 - order.retainageRate / 100); return <article key={order.id} style={panel}><div style={eyebrow}>{order.workOrderNumber} · {order.tradePackage}</div><h2 style={{ margin: "7px 0 0", fontSize: 21 }}>{order.subcontractor}</h2><div style={muted}>{order.milestone}</div><div style={barTrack}><div style={{ ...bar, width: `${progress}%` }} /></div><div style={statLine}><span>Progress {progress.toFixed(1)}%</span><span>₹{net.toLocaleString("en-IN")} net certified</span></div><div style={{ marginTop: 16, color: order.masterIpcFunded ? "#86efac" : "#fcd34d", fontSize: 12, fontWeight: 800 }}>{order.masterIpcFunded ? "IPC funded · payment gate open" : "PAY-WHEN-PAID HOLD · IPC unfunded"}</div><button type="button" onClick={() => setSelected(order)} style={button}>Open work order detail</button></article>; })}</section>{selected && <WorkOrderDetailModal order={selected} onClose={() => setSelected(null)} onSave={(updated) => { setOrders((current) => current.map((item) => item.id === updated.id ? updated : item)); setSelected(null); }} />}</div></main>; }
const page: React.CSSProperties = { minHeight: "100vh", background: "#050816", color: "#e2e8f0", padding: 28 }; const container: React.CSSProperties = { maxWidth: 1300, margin: "0 auto" }; const header: React.CSSProperties = { marginBottom: 24 }; const eyebrow: React.CSSProperties = { color: "#67e8f9", fontSize: 11, letterSpacing: ".16em", textTransform: "uppercase" }; const title: React.CSSProperties = { margin: "8px 0 0", fontSize: 38 }; const muted: React.CSSProperties = { color: "#94a3b8", fontSize: 12, marginTop: 6 }; const grid: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))", gap: 16 }; const panel: React.CSSProperties = { background: "#0b1220", border: "1px solid #1e293b", borderRadius: 16, padding: 20 }; const barTrack: React.CSSProperties = { height: 9, marginTop: 22, background: "#111827", borderRadius: 999, overflow: "hidden" }; const bar: React.CSSProperties = { height: "100%", background: "linear-gradient(90deg,#38bdf8,#34d399)", borderRadius: 999 }; const statLine: React.CSSProperties = { display: "flex", justifyContent: "space-between", gap: 10, color: "#cbd5e1", fontSize: 12, marginTop: 8 }; const button: React.CSSProperties = { marginTop: 18, border: "1px solid #334155", borderRadius: 8, background: "transparent", color: "#cbd5e1", padding: "9px 11px", cursor: "pointer", fontWeight: 800 };